### ISSUE TITLE
Resolved Profile Catalogs are Missing Parameter Properties

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#1003]
### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [X] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP OSCAL Validations**

### What happened?

The FedRAMP resolved profile catalogs are being generated without the NIST SP 800-53 parameter properties (`//control/param/prop`).

Upon a spot check, this appears to be consistent for every parameter that has one or more properties in the 800-53 catalog.

### How do we replicate this issue?

- Open the [NIST SP 800-53 r5 catalog](https://raw.githubusercontent.com/usnistgov/oscal-content/refs/tags/v1.3.0/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml)
  - Find any parameter that contains properties. For example, AC-1's first parameter (`ac-1_prm_1`)
  - Observe properties

```
      <param id="ac-1_prm_1">
        <prop name="aggregates" ns="http://csrc.nist.gov/ns/rmf" value="ac-01_odp.01"/>
        <prop name="aggregates" ns="http://csrc.nist.gov/ns/rmf" value="ac-01_odp.02"/>
        <label>organization-defined personnel or roles</label>
      </param>
      <param id="ac-01_odp.01">
        <prop name="label" class="sp800-53a" value="AC-01_ODP[01]"/>
        <label>personnel or roles</label>
        <guideline>
          <p>personnel or roles to whom the access control policy is to be disseminated is/are defined;</p>
        </guideline>
      </param>
      <param id="ac-01_odp.02">
        <prop name="label" class="sp800-53a" value="AC-01_ODP[02]"/>
        <label>personnel or roles</label>
        <guideline>
          <p>personnel or roles to whom the access control procedures are to be disseminated is/are defined;</p>
        </guideline>
      </param>
```

- Open the [FedRAMP HIGH Profile](https://raw.githubusercontent.com/GSA/fedramp-automation/refs/heads/develop/dist/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline_profile.xml)
  - Observe there are no `remove` statements.

- Open the [FedRAMP HIGH Resolved Profile Catalog](https://raw.githubusercontent.com/GSA/fedramp-automation/refs/heads/develop/dist/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.xml)
  - View the same parameter
  - Observe there are no properties (the properties observed above are missing)

```
         <param id="ac-1_prm_1">
            <label>organization-defined personnel or roles</label>
         </param>
         <param id="ac-01_odp.01">
            <label>personnel or roles</label>
            <guideline>
               <p>personnel or roles to whom the access control policy is to be disseminated is/are defined;</p>
            </guideline>
         </param>
         <param id="ac-01_odp.02">
            <label>personnel or roles</label>
            <guideline>
               <p>personnel or roles to whom the access control procedures are to be disseminated is/are defined;</p>
            </guideline>
         </param>
```

### Where, exactly?

This relates to generation of resolved profile catalogs from profiles. The issue is likely in the mechanism that performs the conversion.

**Comment by aj-stein-gsa** [comment]
Per discussion in Google Chat, observation of the missing `prop`s was based in understanding a discrepancy in a PR. There is not an immediate need, but is something we will resolve in a subsequent release (alpha and final) by promoting content into `master`. If we need to, we can reopen accordingly.
