### ISSUE TITLE
Security Controls - SSP has correct controls

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#1004]
### Constraint Task

As a consumer of FedRAMP automated completeness checks, I want to make sure submitted SSPs address all of the correct FedRAMP baseline controls and don't include extraneous controls.

### Intended Outcome

**For each control in the baseline (resolved profile catalog)**
- [ ]  an implemented requirement must be present in the SSP.

**For each control in the SSP**
- [ ]  Is the control absent from the imported baseline (resolved profile catalog)?

### Syntax Type

This is a mix of required, optional, and/or extended syntax.

### Allowed Values

There are no relevant allowed values.

### Metapath(s) to Content

```xslt
**For each control in the baseline (resolved profile catalog)**

- `metapath target="/catalog//control"`
- VAR: `control-label`
  - EXPRESSION: `"./prop[@name='label' and not(@Class) and (not(@ns) or @ns='http://csrc.nist.gov/ns/oscal/1.0') ]/@value"`
- VAR: `baseline-title`
  - EXPRESSION: `"/catalog/metadata/title"`


- [ ]  For each control in the baseline (resolved profile catalog), an implemented requirement must be present in the SSP.
  - EXPECT:
  - `target="."`
  - `test="exists(/system-security-plan/control-implementation/implemented-requirement[@control-id=./@id] = 1)"`  
  - ERROR: The $control-label control exists in the $baseline-title, but is missing from the SSP.

**For each control in the SSP**
`metapath target='/system-security-plan/control-implementation/implemented-requirement'`

- [ ]  Is the control absent from the imported baseline (resolved profile catalog)?
  - `target='.'`
  - `expect(count(/catalog//control[@id=./@control-id]) = 0)`
  - WARNING: A control with ID [./@control-id] exists in the SSP, but is not defined in the baseline. Controls can not be properly assessed or adjudicated if they have not been added to the baseline, such as with an profile overlay.
```

### Purpose of the OSCAL Content

This validation check helps reviewers ensure that submitted SSPs address all of the controls in the referenced FedRAMP baseline and warns them if extraneous controls that are not part of the FedRAMP baseline are included in the SSP.

### Acceptance Criteria

- [ ] All [OSCAL adoption content](http://automate.fedramp.gov/) affected by the change in this issue have been updated in accordance with the Documentation Standards.
  - [ ] Explanation is present and accurate
  - [ ] sample content is present and accurate
  - [ ] [Metapath](https://pages.nist.gov/metaschema/specification/syntax/metapath/) is present,  accurate, and does not throw a syntax exception using `oscal-cli metaschema metapath eval -e "expression"`. 
- [ ] All constraints associated with the review task have been created
- [ ] The appropriate example OSCAL file is updated with content that demonstrates the FedRAMP-compliant OSCAL presentation.
- [ ] The constraint conforms to the FedRAMP Constraint Style Guide. 
  - [ ] All automated and manual review items that identify non-conformance are addressed; **or** technical leads (David Waltermire; AJ Stein) have approved the PR and “override” the style guide requirement.
- [ ] Known good test content is created for unit testing.
- [ ] Known bad test content is created for unit testing.
- [ ] Unit testing is configured to run both known good and known bad test content examples.
- [ ] Passing and failing unit tests, and corresponding test vectors in the form of known valid and invalid OSCAL test files, are created or updated for each constraint.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals section of the User Story in the issue. 
- [ ] This issue is referenced in the PR.

### Other information

See https://github.com/GSA/fedramp-automation/issues/810#issuecomment-2521235078 for additional details.

**Comment by wandmagic** [comment]
https://github.com/GSA/fedramp-automation/pull/981 covers this fully
