### ISSUE TITLE
Security Controls - SSP has statement for each control _statement_ response point

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#1005]
### Constraint Task

As a consumer of FedRAMP automated completeness checks, I want to make sure that control statement responses are provided for every baseline control  statement response point.

### Intended Outcome

- [x]  For each response point within the control's statement, there must be a statement within the correct control in the SSP.

### Syntax Type

This is a mix of required, optional, and/or extended syntax.

### Allowed Values

There are no relevant allowed values.

### Metapath(s) to Content

```xslt
For each response point within the control's statement, there must be a statement within the correct control in the SSP.

 - NOTE: We need to be careful to avoid response points in assessment objectives.
 - metapath target="./part[@name='statement' and ./prop[@name='response-point' and @ns='https://fedramp.gov/ns/oscal']]/@id"
 - metapath target="./part[@name='statement']//part[@name ='item' and ./prop[@name='response-point' and @ns='https://fedramp.gov/ns/oscal']]/@id"
 - VAR: statement-label
  - EXPRESSION: "./prop[@name='label' and not(@Class) and (not(@ns) or @ns='http://csrc.nist.gov/ns/oscal/1.0') ]/@value"
 - count(/system-security-plan/control-implementation/implemented-requirement/statement[@statement-id=./@id]) = 1
  - NOTE: I would prefer to also ensure this statement is correctly aligned under the correct implemented requirement, but am unsure how to reflect that in metaschema. In other words, it would be better if this looked something like this: count(/system-security-plan/control-implementation/implemented-requirement[@control-id='ac-1']/statement[@statement-id='ac-1_smt.a') = 1
 - ERROR: A response is required for $control-label $statement-label, but is not found from the SSP.
```

### Purpose of the OSCAL Content

This validation check helps reviewers ensure that submitted SSPs address all of the control requirements at the appropriate granularity, and also detects any extraneous (control implementation) statements.

### Acceptance Criteria

- [ ] All [OSCAL adoption content](http://automate.fedramp.gov/) affected by the change in this issue have been updated in accordance with the Documentation Standards.
  - [ ] Explanation is present and accurate
  - [ ] sample content is present and accurate
  - [ ] [Metapath](https://pages.nist.gov/metaschema/specification/syntax/metapath/) is present,  accurate, and does not throw a syntax exception using `oscal-cli metaschema metapath eval -e "expression"`. 
- [ ] All constraints associated with the review task have been created
- [ ] The appropriate example OSCAL file is updated with content that demonstrates the FedRAMP-compliant OSCAL presentation.
- [ ] The constraint conforms to the FedRAMP Constraint Style Guide. 
  - [ ] All automated and manual review items that identify non-conformance are addressed; **or** technical leads (David Waltermire; AJ Stein) have approved the PR and “override” the style guide requirement.
- [ ] Known good test content is created for unit testing.
- [ ] Known bad test content is created for unit testing.
- [ ] Unit testing is configured to run both known good and known bad test content examples.
- [ ] Passing and failing unit tests, and corresponding test vectors in the form of known valid and invalid OSCAL test files, are created or updated for each constraint.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals section of the User Story in the issue. 
- [ ] This issue is referenced in the PR.

### Other information

See https://github.com/GSA/fedramp-automation/issues/810#issuecomment-2521235078 for additional details.

**Comment by wandmagic** [comment]
see #1020
