### ISSUE TITLE
[Question]: Validation logic for control-origination

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#1012]
### This is a ...

question - need to understand something

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [X] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### What is your feedback?

We were wondering what external constraints might be implemented in the future for validating the "control-origination" props for implemented-requirements, and if there will be different validation requirements for the -1 controls (AC-1, PE-1, etc.). We noticed there aren't currently any external constraints for this, and just want to make sure our logic will support them in the future if they are added.

### Where, exactly?

- OSCAL v1.1.2
- fedramp external constraints

**Comment by aj-stein-gsa** [comment]
Thanks for your timely and important questions as always, @Telos-sa. At this time, we are updating our understanding of the control origination requirements for current FedRAMP review processes. Stay tuned to #868 as well develop the documentation for latest updates. They should be happening soon. I would recommend subscribing to notifications on that issue moving forward.

I am going to close this question for now. If you have follow-up questions in the short-term, or during or after the work on #868, please re-open this question issue or open a new one and we will work with you to answer your questions or concerns to the best of our ability.
