### ISSUE TITLE
Cross-Check for OSCAL and FedRAMP Allowed Values and Constraints

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#115]
# Action Item

**This is a ...**
  - [X] **investigation** - Something needs to be investigated further.

**This relates to ...**
  - [X] **General/Overall**
  - [X] **Other**

NOTE: For issues related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

## Describe the problem or enhancement

{A clear and concise description of the problem or enhancement.}

## Goals:

{A clear and concise description of what you want to happen. This should be outcome focused. Include concise description of any alternative solutions or features you've considered. Feel free to include screenshots or examples about the feature request here.}

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

## Other Comments

{Add any other context about the problem here.}

**Comment by ohsh6o** [comment]
More details to come but per our conversation this afternoon, @david-waltermire-nist and @wendellpiez.

**Comment by ohsh6o** [comment]
Actively picking this work back up again and updating with review of changes in usnistgov/OSCAL#1012.

**Comment by aj-stein-nist** [comment]
@volpet2014 this is the story work I was discussing during our touch-base today.

**Comment by volpet2014** [comment]
Consulted with NIST on this.   We are planning a pairing session with NIST, PMO, Reviewers and tech leads to discuss this in the near future.

**Comment by volpet2014** [comment]
Need to check with @Rene2mt  with regards to resolving inconsistencies and differences and reflect in Guides documentation also.

**Comment by aj-stein-gsa** [comment]
As we have begun to build out the new external constraints approach, we have started to make this cross-check review part of the normal development and review process with the advent of the [`oscal-external-constraints`](https://github.com/GSA/fedramp-automation/blob/41d76e9788f97347ddf13955743dd28b044efec6/src/validations/constraints/oscal-external-constraints.xml), the style guide, and the intent to upstream them. It is a more continual process and will not be a static epic with sub-tasks. My initial issue and updated recommendation as a NIST advisor were oft the mark, so now I am closing this one out as "not planned."

We have a better way to do this continuously.
