### ISSUE TITLE
Branch Protection Breaks Validaton, Conversion, and Publication Automation

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#117]
# Describe the bug

When [enabling Github branch protection](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule), this prevents [the oscalbuilder automation user](github.com/oscalbuilder) used by NIST and FedRAMP to automate validation and conversion of artifacts.

This is [recommended for version control considerations with ATO](https://handbook.tts.gsa.gov/getting-started/#github-and-version-control) in mind for GSA TTS ATO process (not specific to any sensitivity level), but will break our build process.

# Who is the bug affecting?

FedRAMP CI/CD processes and organizational risk management and security engineering considerations.

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

`v1.0.0` pinned under current submodule.

# What is affected by this bug?

FedRAMP Automation Team

# When does this occur?

When FAT developers or 10x ASAP validation developers merge code, the subsequent automated artifact build will fail.

# How do we replicate the issue?

1. Merge any pull request to `master`.

# Expected behavior (i.e. solution)

The automated oscalbuilder process through Github Actions will not be rejected by branch protections.

**Comment by ohsh6o** [comment]
Per conversation with Dave, perhaps consider converting to an automation user opening a PR and not just auto-committing if there is a concern with that kind of thing.

**Comment by ohsh6o** [comment]
Given discussion in [GSA TTS Slack about prevailing guidance re this approach](https://gsa-tts.slack.com/archives/C02KXM98G/p1627069839027200), move back until further examination of alternate auth schemes for the git commit action we use to push changes can be performed.

**Comment by volpet2014** [comment]
Leaving open at this point until resolution in alignment with NIST CI/CD workflows.

**Comment by aj-stein-gsa** [comment]
This is very old and GitHub features evolved. We now have more comprehensive branch protections with GitHub rulesets. Goodbye, old @ohsh6o AJ!
