### ISSUE TITLE
Automate File Type Conversion Checks

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#129]
# Action Item

**This is a ...**
  - [X] **fix** - Something needs to be different.

**This relates to ...**
  - [X] **Other**

## Describe the problem or enhancement

This is a follow-on for ongoing development effort for the NIST OSCAL CI/CD to address ongoing work that was not complete for GSA/fedramp-automation#103.

## Goals:

When common document instances are converted between XML and JSON and YAML in the NIST OSCAL CI/CD system, file paths are presumed to be similar and then [extensions are switched out by a `perl`-based regex that does the file extension substitution](https://github.com/usnistgov/OSCAL/blob/0858d4ff7ddc60db113628eab75e161ddc1fff10/build/ci-cd/copy-and-convert-content.sh#L152-L164). This has broken for a period, which led to the linked issue and relevant issue for the NIST OSCAL content repo, usnistgov/oscal-content#59.

## Dependencies:

None

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by ohsh6o** [comment]
FYI, @rgauss since it is a source of all the kludges in the repo fork you maintain: I have made some headway on this effort so that you and all other NIST OSCAL/FedRAMP consumers can make use of OSCAL documents, hopefully, and get converted file-types and not have to work around it. I will require adding in a Python script to the CI/CD processing, and it turned out a little more complicated than I planned. Simply switching out `xml` for `json` is not always ideal and I went down a rabbit hole to find a structured way to resolve it. More to follow!

**Comment by volpet2014** [comment]
This will be resolved when FedRAMP Automation #241 is closed.

**Comment by aj-stein-gsa** [comment]
This issue seems very likely easy to close given the changes in code and infrastructure in ... wow ... more than three years, but I need to double check what we will do with these paths and files moving forward with #738. Will close this for now.

By old @ohsh6o AJ. 👋
