### ISSUE TITLE
Create Unique CI/CD User

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#132]
# Action Item

**This is a ...**
  - [X] **enhancement** - Something could be better.

**This relates to ...**
  - [X] **Other**

## Describe the problem or enhancement

NIST has an [oscalbuilder user](https://github.com/oscalbuilder) user that is shared in our build process. In consultation with NIST OSCAL developers, it is clear that is not sustainable in the long-term and we should fix our copy of the CI/CD system to use its own user.

## Goals:

Clear separation of concerns and least privilege for users (even if automated) .

## Dependencies:

- [ ] GSA Policy requirements for automated accounts in Github.
- [ ] Implementation possibilities for provisioning and ongoing management.

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by ohsh6o** [comment]
Created [fedramp-builder](https://github.com/fedramp-builder) for this purpose. Need to understand how to manage a CI-CD user account in alignment with organizational policy.

**Comment by volpet2014** [comment]
Will need to addres son Rev 5 update release and cycle a new oscalbuilder key.

**Comment by aj-stein-nist** [comment]
> Will need to addres son Rev 5 update release and cycle a new oscalbuilder key.

Per our discussion, as an interim measure, before #241 lands as a medium to long-term approach, I would strongly recommend we switch to a [an "Allow write access"  SSH deploy key](https://github.com/GSA/fedramp-automation/settings/keys/new) and add that as the updated `SSH_PRIVATE_KEY` in the Actions Secrets configuration fort his repo.

**Comment by aj-stein-gsa** [comment]
In the near future will likely change approach and a unique user to write back content will not be strictly needed. I will close this issue for now and only open if appropriate or necessary during the [post-ADR-7 cleanup](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md). But linking to #738 for awareness and review.
