### ISSUE TITLE
SSP-A04-FedRAMP-PIA-Template

### ISSUE THREAD

**Issue by cmckerliesr** [GSA/fedramp-automation#133]
* **This is a ...**
  - [X
[SSP-A04-FedRAMP-PIA-Template.docx](https://github.com/GSA/fedramp-automation/files/6793670/SSP-A04-FedRAMP-PIA-Template.docx)
 ] **concern** - I think something needs to be different.
  - [ ] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [X ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

* **What is your feedback?**
It in section 3.2 page 3, there are two Controls one embedded inside the other and in other cases, there are three or more document controls embedded inside each other.

Also, you should not give all the document controls the same Title or tag unless you intend it to repeat the same text from that control throughout the document. For example your Information System Name control. 
To do this right and stop issues, remove the redundant Word Controls, and rename what is left behind as Explanation 1, Explination2, etc., then there are no issues. OR, just do all of us a favor and remove the Explanation document controls all together and format the cell left behind for text with italics.

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

* **What action would you like to see from the FedRAMP PMO?**

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)
It in section 3.2 page 3, there are two Controls one embedded inside the other and in other cases, there are three or more document controls embedded inside each other.

Also, you should not give all the document controls the same Title or tag unless you intend it to repeat the same text from that control throughout the document. For example your Information System Name control. 
To do this right and stop issues, remove the redundant Word Controls, and rename what is left behind as Explanation 1, Explination2, etc., then there are no issues. OR, just do all of us a favor and remove the Explanation document controls all together and format the cell left behind for text with italics.

Also, if you are going to create a template, you should publish as a Word Template (*.dotx).

**Comment by ohsh6o** [comment]
@cmckerliesr, thanks for your report to FedRAMP. We greatly appreciate it!

I see you have a lot of feedback. At this time, the PIA Word template file (DOCX or aspirationally a DOTX file) are not artifacts managed through this repository or the FedRAMP Automation Team's code or continuous deployment process here. Per the footer of the document you referenced, it is recommended you report these findings through the main helpdesk.

> How to contact us
For questions about FedRAMP, or for technical questions about this document including how to use it, contact info@fedramp.gov 
For more information about the FedRAMP project, see www.fedramp.gov

If you would like guidance on an OSCAL variant of this document, please open a new request here and I will work with the PMO to prioritize it.

Additionally, I will clarify our issue templates to ask about the Word variants and to properly direct support inquiries to info@fedmrap.gov.
