### ISSUE TITLE
SSP Guidance for "This System" Components, Prop Namespaces, and Other Errata Improvements

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#141]
* **This is a ...**
  - [X] **concern** - I think something needs to be different.

* **This relates to ...**
  - [X] the **FedRAMP OSCAL Registry** (Excel File)
  - [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
 
* **Where, exactly?**

Thanks to @GaryGapinski from [the 10x ASAP development partners](https://github.com/orgs/GSA/teams/fedramp-automation-validation-partners), he reported directly to me the following issues.

- [x] Page 42 of DRAFT Guide to OSCAL-based FedRAMP System Security Plans has a “this-system” component, but page 63 has a “system” component. Both appear to discuss the same entity. FedRAMP-SSP-OSCAL-Template.xml [uses](https://github.com/18F/fedramp-automation/blob/dd576c7541c1c924890c27f15d5595aef469622f/src/validations/test/demo/FedRAMP-SSP-OSCAL-Template.xml#L706-L712) the page 42 variant.
- [x] Oddities like: is the (impossible, since only components can have a type attribute of `validation`) use of an inventory-item for CMVP (page 59). And since crypto is used in all modern systems, the cardinality should be 1-∞.
- [x] Page 54 has vendor-name in FedRAMP namespace but FedRAMP-SSP-OSCAL-Template.xml does not.
- [X] ~Page 57 hardware-model is not in FedRAMP namespace but possibly should be.~
- [X] ~Pages 56-59 asset categories are vague, e.g. “infrastructure” has no specific mapping to asset-type.~ Follow up on this in GSA/fedramp-automation#146.
- [X] Page 59 et al. “FIPS 140-2” will be superseded/obsolescent because of FIPS 140-3. Generalize wording for FIPS-140 family, as opposed to FIPS 140-3, in certain cases.
- [x] Page 64 does not match the [template](https://github.com/18F/fedramp-automation/blob/dd576c7541c1c924890c27f15d5595aef469622f/src/validations/test/demo/FedRAMP-SSP-OSCAL-Template.xml#L761-L771)
- [x] Regarding the “this-system” component: the fedramp_values.xml document does not enumerate that type.
- [x] DRAFT Guide to OSCAL-based FedRAMP System Security Plans §5.3 shows implementation-status prop in FedRAMP namespace (ns attribute) but FedRAMP-SSP-OSCAL-Template.xml does not.
- [x] DRAFT Guide to OSCAL-based FedRAMP System Security Plans §5.3.1.1 shows control-origination and leveraged-authorization-uuid props in FedRAMP namespace (ns attribute) but FedRAMP-SSP-OSCAL-Template.xml does not.
- [x] DRAFT Guide to OSCAL-based FedRAMP System Security Plans §5.3.1.1 example <leveraged-authorization> lacks uuid attribute and has prohibited attributes.

* **What is your feedback?**
 
See above.

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

`fedramp1.0.0-oscal1.0.0`

* **What action would you like to see from the FedRAMP PMO?**

Make document and code changes accordingly.

**Comment by GaryGapinski** [comment]
DRAFT Guide to OSCAL-based FedRAMP System Security Plans §5.3 shows `implementation-status` `prop` in FedRAMP namespace (`ns` attribute) but `FedRAMP-SSP-OSCAL-Template.xml` does not.

DRAFT Guide to OSCAL-based FedRAMP System Security Plans §5.3.1.1
- shows `control-origination` and `leveraged-authorization-uuid` `prop`s  in FedRAMP namespace (`ns` attribute) but `FedRAMP-SSP-OSCAL-Template.xml` does not.
- example `<leveraged-authorization> lacks `uuid` attribute and has prohibited attributes.

**Comment by ohsh6o** [comment]
@GaryGapinski, it seems the `asset-type` should align with NIST OSCAL values in the short-term, and default to the NIST values (without the FedRAMP `ns`) in the long-term. See [this reference](https://pages.nist.gov/OSCAL/reference/latest/component-definition/xml-reference/#/component-definition/component/prop/@name) for details.

**Comment by GaryGapinski** [comment]
I concur (that `asset-type` should align with NIST OSCAL values) (except for FedRAMP-specific `asset-type`s which remain durably FedRAMP-specific).

**Comment by ohsh6o** [comment]
`hardware-model` not being in the FedRAMP `ns` at this point is intentional, re page 57 report. I had to double-check.

**Comment by ohsh6o** [comment]
@GaryGapinski, so I gave this some thought re the following item in your bug report (and seriously, thanks again for this):

> Pages 56-59 asset categories are vague, e.g. “infrastructure” has no specific mapping to asset-type.

From the note in Section 6.5.1, let us consider the following rationale.

> NOTES: 
> The value of asset-type determines whether the identified asset-administrator is managing a system or an application. 

I think it is best that we follow that and consider anything with a set asset-type is infrastructure, and thus should be scanned in some way as `@scan-type="infrastructure"` as a superset of not just server ("`os`" items) but anything with an `asset-type` for now because none of those, any value in the FedRAMP values for `asset-type`, really represent "an application" (unless you were operating a General Support Service or Enterprise Shared Service as the information system in scope, but you likely still have "applications in there"), so I will keep them as is an open an enhancement story (since it is not bug worthy and could be a breaking change) to later expand this and clarify it.

Thanks again, that minor issue gave us a lot to think about. :-)

**Comment by ohsh6o** [comment]
@GaryGapinski , also updated the note to say (PR forthcoming):

> NOTES: 
> The value of asset-type determines whether the identified asset-administrator is managing a system or an application. Currently, any FedRAMP-defined asset-type implies the management of a system, and therefore, is to be scanned as infrastructure.

**Comment by GaryGapinski** [comment]
Then are the following correct?
- the presence of a `<prop name="scan-type>` conveys that an `<inventory-item>` (or `<component>`) is one of (infrastructure or database or web-server) despite the presence or absence of a `<prop name="asset-type">`
- the absence of a `<prop name="scan-type>` conveys that an `<inventory-item>` (or `<component>`) is not any of (OS/Infrastructure or Software or Database) despite the presence or absence of a `<prop name="asset-type">`

**Comment by ohsh6o** [comment]
@GaryGapinski, as it stands, I am saying `intentory-item` or `component` that has any `asset-type` from the [`asset-type` enum/allowed-values` list is inherently OS or infrastructure, and thereby _must have_ a `scan-type` of [`infrastructure`](https://github.com/GSA/fedramp-automation/blob/9fbc1d2912049316227ec77e965f7651b9904560/dist/content/resources/xml/fedramp_values.xml#L349). Does that make sense? If you asset-type is _not_ from that list, I expect you to be a scan type of `database` or `other` or `web`. I guess I might be able to tighten up the values, but that seems the cleanest and simplest interpretation of our docs for now.
