### ISSUE TITLE
GSA and FedRAMP Standards to Clarify DoD

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#144]
**Extended Description**

As a FedRAMP representative, to understand this software meets security engineer requirements of GSA and FedRAMP, I want clear explanation of FedRAMP security engineering standards.

**Preconditions**
- [ ] Defined standards endorsed from FedRAMP: be it GSA, or TTS, or standards of their own endorsed by the PMO.

**Acceptance Critera**
- [ ] Documented explanation of how we meet security engineering activities that meet FedRAMP requirements.
- 

**Story Tasks**
- [ ] Tasks...

(NOTE: We cannot transfer tasks between the 18F and GSA org, so this is copy-pasted from 18F/fedramp-automation#73.)

**Comment by aj-stein-gsa** [comment]
Wow, hello old @ohsh6o AJ. It would seem this is still as relevant as ever, but also partially completed with @brian-ruf's work in #824. So for now, I will mark this as closed and reopen with more focused requirements.
