### ISSUE TITLE
JSON Templates Reference XML Imports 

### ISSUE THREAD

**Issue by rgauss** [GSA/fedramp-automation#145]
# Describe the bug

Similar to #103, the JSON templates contain imports that reference XML rather than JSON files.

For example, the SSP template [import-profile points to the XML moderate profile](https://github.com/GSA/fedramp-automation/blob/master/dist/content/templates/ssp/json/FedRAMP-SSP-OSCAL-Template.json#L696).

# Who is the bug affecting?

Anyone attempting to use JSON-based tooling to resolve controls for the JSON templates.

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

No.

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

1.0.0

# What is affected by this bug?

Prevents controls from being resolved by JSON tooling.

# When does this occur?

Always

# How do we replicate the issue?

Use JSON-based tooling to attempt to resolve template controls

# Expected behavior (i.e. solution)

The templates should reference JSON imports.

# Other Comments

**Comment by ohsh6o** [comment]
@rgauss, thanks as always for your actionable feedback. It appears this is part of GSA/fedramp-automation#129. I will track that work there and update you when this CI/CD workaround is complete. As you may know, this will be more systematically reviewed with Metaschema and OSCAL development in core, outside of this CI/CD effort, in the long-term while working with the NIST OSCAL Team.

**Comment by volpet2014** [comment]
Closing- resolved in #241

**Comment by volpet2014** [comment]
Will be resolved by #241.
