### ISSUE TITLE
Clarify Asset Type for "Infrastructure" and Application Types

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#146]
* **This is a ...**
  - [X] **concern** - I think something needs to be different.
  - [X] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [X] **General/Overall**

Per feedback in [141](https://github.com/GSA/fedramp-automation/issues/141#issuecomment-885277659), consider further expanding the dichotomy between infrastructure and non-infrastructure inventory items to clarify the additional FedRAMP requirements as expressed in OSCAL.

**Comment by aj-stein-gsa** [comment]
This no longer seems applicable. Goodbye, old @ohsh6o AJ.
