### ISSUE TITLE
control-origination value mismatch

### ISSUE THREAD

**Issue by GaryGapinski** [GSA/fedramp-automation#151]
# Describe the bug

`control-origination` property values in [`FedRAMP-SSP-OSCAL-Template.xml`](https://github.com/GSA/fedramp-automation/blob/master/dist/content/templates/ssp/xml/FedRAMP-SSP-OSCAL-Template.xml#L1109) do not match acceptable values defined in [`fedramp_values.xml`](https://github.com/GSA/fedramp-automation/blob/master/dist/content/resources/xml/fedramp_values.xml#L425-L436). 

# Who is the bug affecting?
Users of fedramp-automation content.

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)
No.

# What version of OSCAL are you using?
```
<oscal-version>1.0.0</oscal-version>
<version>fedramp1.0.0-oscal1.0.0</version>
```

# What is affected by this bug?

Unacceptable values are considered errors.

# When does this occur?

Durably until corrected.

# How do we replicate the issue?

Observe control-origination properties in [`FedRAMP-SSP-OSCAL-Template.xml`](https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/templates/ssp/xml/FedRAMP-SSP-OSCAL-Template.xml) using an XPath statement `//prop[@name='control-origination']`

# Expected behavior (i.e. solution)

`control-origination` values should conform to those in [`fedramp_values.xml`](https://github.com/GSA/fedramp-automation/blob/master/dist/content/resources/xml/fedramp_values.xml#L425-L436).

# Other Comments

The values in [`fedramp_values.xml`](https://github.com/GSA/fedramp-automation/blob/master/dist/content/resources/xml/fedramp_values.xml#L425-L436) are consonant with those in section §5.3.1.1 of [the SSP Guide](https://github.com/GSA/fedramp-automation/blob/master/documents/Guide_to_OSCAL-based_FedRAMP_System_Security_Plans_(SSP).pdf).

**Comment by ohsh6o** [comment]
@GaryGapinski, thanks for reporting this. I will address this in a PR today. Also, you provided follow-up feedback about control-origination, in addition to this bug report. I will be addressing those in an updated patch release soon.
