### ISSUE TITLE
Developed FedRAMP content in OSCAL

### ISSUE THREAD

**Issue by mzia** [GSA/fedramp-automation#161]
FedRAMP baselines using OSCAL can’t really use http://GitHub.com to store package content as it is a LiSaaS.   GSA /FedRAMP must have a moderately ATOed SaaS system in place as fully developed package will contain CUI and other sensitive data saved to a version control system as source code.  This makes a need for standing up a Gitlab or something like it across GSA more important otherwise it will become a blocker during adoption.

**Comment by sunstonesecure-robert** [comment]
the current guidance from the PMO as I understand it is to use MAX.gov and drop the OSCAL file where you would ordinarily drop the Word or Excel file.  If anyone knows differently, please advise.

**Comment by volpet2014** [comment]
Moved to FedRAMP PMO Policy discuss board for further analysis and discussion.
