### ISSUE TITLE
Clarify OSCAL-Based CRM Model and Examples

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#179]
* **This is a ...**
  - [X] **concern** - I think something needs to be different.
  - [X] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [X] **General/Overall**
  - [X] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **What is your feedback?**

Complete ground worked needed for 18F/fedramp-automation#301.

* **What action would you like to see from the FedRAMP PMO?**

Review and buy-in from FR PMO on approach recommended by FR OSCAL support engineer.

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

N/A

**Comment by aj-stein-gsa** [comment]
This is an older issue that is obsoleted and will be replaced by significant rework during and after the pilot. I will close this issue for now. Goodbye, old @ohsh6o AJ!
