### ISSUE TITLE
Broad github issue template feedback

### ISSUE THREAD

**Issue by JJediny** [GSA/fedramp-automation#19]
As a respondent to a new issue:
- it's often easier to delete options to select than it is to edit a checkbox in raw markdown, a note at the beginning to delete bullets not relevant is often easier to get right.:
    - [ ] editing to (in raw markdown - requires knowledge of markdown... to...
    - [x] to indicate a selection, suggest asking users to delete whatever is not relevant to their submittal.
- Instead of using **bold**, use H3 or H4 in `### H3` `#### H4` as it is visually cleaner to the respondent.
- for NOTE: suggest using `>NOTE:`
- `other` section e.g./example might be better to exclude and leave open-ended, as `Additional Information`.
---
## Example of suggested fixes...

>Please delete bullets/items not relevant to make a selection

### This is a:
  - **concern** - I think something needs to be different.
  - **question** - I didn't understand something.
  - **kudo** - I found something helpful and want to encourage it in future FedRAMP publications.
  - **request** - I would like to see something additional provided.

### This relates to:
  - the **FedRAMP OSCAL Registry** (Excel File)
  - the **Modeling a FedRAMP SSP in OSCAL Guide** (PDF)
  - the **FedRAMP SSP OSCAL Template** (JSON Format)
  - the **FedRAMP SSP OSCAL Template** (XML Format)
  - **General/Overall**
  - **Other** - _Please edit_ 

>NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

#### Specific comment on the Guidance?:
If so, please cite the document(s) and section(s):
  - For the registry, please indicate the tab and cell, or another clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the XML and JSON files, please indicate the line number, field id, or another clear identifier

**Comment by brianrufgsa** [comment]
Thank you @JJediny for the feedback and suggestions.
I addressed this in PR #21.
