### ISSUE TITLE
Clarification of Requirements for import-profile

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#213]
* **This is a ...**
  - [ ] **concern** - I think something needs to be different.
  - [x] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [x] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [x] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

FedRAMP SSP Guide p.8
FedRAMP-SSP-OSCAL-Template.xml Lines 502-508

* **What is your feedback?**

The profile we are using includes more controls than that of the FedRAMP Template Baseline.

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

* **What action would you like to see from the FedRAMP PMO?**

What import profile is expected? Are we able to reference the file path to our own profile in order to capture all controls? Is the baseline XML file required to be included in the export?

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by david-waltermire-nist** [comment]
OSCAL is flexible here. Not sure if FedRAMP wants to be more specific in what is allowed for FedRAMP.
