### ISSUE TITLE
Clarification on <back-matter> resource linkage to controls

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#218]
* **This is a ...**
  - [ ] **concern** - I think something needs to be different.
  - [x] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [x] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [x] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

* **What is your feedback?**

* **Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)** If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

1.0.2

* **What action would you like to see from the FedRAMP PMO?**

In the FedRAMP SSP example, the artifacts (`<back-matter>` resources) are only tied to certain controls.  What is the requirement / limitation of linking artifacts – since Xacta will be leveraging local types. 
What resource types are required for validation?

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by volpet2014** [comment]
We currently look for specific resource types.  See  https://github.com/GSA/fedramp-automation/blob/master/dist/content/resources/xml/fedramp_values.xml for a list.   FedRAMP may consider allowing additional types in a future update if this becomes an issue for other tool implementers.

**Comment by telosBA** [comment]
> We currently look for specific resource types. See https://github.com/GSA/fedramp-automation/blob/master/dist/content/resources/xml/fedramp_values.xml for a list. FedRAMP may consider allowing additional types in a future update if this becomes an issue for other tool implementers.

Will FedRAMP specify what values must be present for validation in the future?

**Comment by volpet2014** [comment]
Just started working through issue with NIST see "FedRAMP Profiles Uses Vendored Media Types Not Conformant with OSCAL & IANA Media Type Specification #232".
