### ISSUE TITLE
Can there be multiple Cloud Service Model props in <system-characteristics>?

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#220]
* **This is a ...**
  - [ ] **concern** - I think something needs to be different.
  - [x] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [x] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

FedRAMP-SSP-OSCAL-Template.xml Line 529

* **What is your feedback?**

There may be use cases in which customers have multiple Cloud Service Models. The template only has one shown.

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

1.0.2

* **What action would you like to see from the FedRAMP PMO?**

Can there be multiple `<prop>` name="cloud-service-model" props (e.g. combination of SaaS, PaaS, IaaS, and Other) in `<system-characteristics>` or is it limited to 1 (mutually exclusive)?

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by david-waltermire-nist** [comment]
OSCAL allows the `prop[@name="cloud-service-model"]` to be repeated, allowing multiple models to be provided. This is a general pattern in OSCAL, allowing multiple values to be provided by using multiple props with the same name and namespace.

I am not sure if FedRAMP wants to restrict this further to a maximum of 1.
