### ISSUE TITLE
UI Validator yields error with relation to pta-4 and SORN ID values

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#239]
# Describe the bug
There is an error in the FedRAMP UI validator. Under System Security Plan Template §15 Attachment 4, there is a test that checks for both PTA-4 to be yes, AND Sorn ID to be provided. By checking for both of these in the same test, it requires PTA-4 to have the value=”yes” regardless of presence of the “sorn-id” prop. (Location: system-characteristics/system-information/prop class=”pta”…) This would be more effective as a conditional test, checking for SORN ID based on the value of PTA-4. (ie. If PTA-4's value is yes, then the SORN ID must exist)

![image](https://user-images.githubusercontent.com/104856767/178504532-bafda9e3-2dfa-4831-a173-5ff4bd7aa96e.png)
![image](https://user-images.githubusercontent.com/104856767/178504552-4e874c05-7971-4e79-8f2c-78a33ec47ad3.png)

# Who is the bug affecting?
Telos

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))
1.0.4

# What is affected by this bug?
Validation through UI

{Describe the impact the bug is having.}

# When does this occur?
Validating XML with UI Validator

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}

1. Generate an XML file with pta-4 value="no"
2. Run generated XML in UI validator
3. See §15 Attachment 4 error

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by danielnaab** [comment]
@telosBA Thanks for the report - this is fixed in 18f/fedramp-automation and available in the Federalist build, and will be merged to GSA/fedramp-automation next week.
