### ISSUE TITLE
Upgrade GitHub CI/CD Workflows to Current Stable Version

### ISSUE THREAD

**Issue by aj-stein-nist** [GSA/fedramp-automation#241]
# User Story:

As an OSCAL tool developer, in order to make sure CI/CD is properly developed and integrated in relevant OSCAL projects, I want the current version of GitHub Actions CI/CD workflows updated to current stable.

## Goals:

The NIST OSCAL Team will assist the FedRAMP PMO's and 10x development team to complete cleaning, deduplification, and misc improvements to the GitHub Actions in [usnistgov/OSCAL](https://github.com/usnistgov/OSCAL/) for improved maintenance, stability, and resiliency.

## Dependencies:

- [ ] Completion of usnistgov/OSCAL#1223

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Story Tasks**
- TBD

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - check in with Wes on what we could do here
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
It would seem we have taken a different approach and our next generation CI will not directly on usnistgov/OSCAL automation, just the source Metaschema and indirect references to assets in submodules. I will mark this as not planned to close.
