### ISSUE TITLE
Should "this-system" be included in the components section?

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#247]
* **This is a ...**
  - [ ] **concern** - I think something needs to be different.
  - [x] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [x] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [x] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

* **What is your feedback?**
There is no reference of the "system" being leveraged as a component in the FedRAMP POAM guide, which results in blanks for tests that were performed at the system level.

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

* **What action would you like to see from the FedRAMP PMO?**
   * Should "this-system" be included in the components section?
   * How should tests that occur at specific locations be addressed?  (Physical control requirements)
   * Should those be relegated to "this-system"?

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by aj-stein-gsa** [comment]
Sorry for the delayed reply to your question. The `component[@type="this-system"]` component is required to be, like others, in the `component` assembly of a SSP and refers to the information system to be authorized. You also mention `component[@type="system"]`, which is for dependency components for leveraged authorizations. Both types still must be defined in the `component`, regardless of which type. We can review the templates, but this confusion is likely the cause.

If we misunderstood your report and we need to revisit it, feel free to open up the issue and clarify.
