### ISSUE TITLE
Related Observation not read by validator

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#255]
# Describe the bug
Related Observation is being passed into the validator, but it is not reading the content

{A clear and concise description of what the bug is.}

# Who is the bug affecting?
Telos 

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))
1.0.4

# What is affected by this bug?
Validation

{Describe the impact the bug is having.}

# When does this occur?
When validating through UI validator

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}

1. Create a POAM json that includes related-observations
![Related-Observations](https://user-images.githubusercontent.com/104856767/188722786-b532641d-b5b3-4021-aaff-a9271b5bc4a1.png)
2. Load the json into the UI validator
3. Note error in section 4.2.1
![Image20220906141944](https://user-images.githubusercontent.com/104856767/188721926-7110ed52-c1f0-46a9-b3ea-ac4f674563a6.jpg)

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by telosBA** [comment]
[OSCAL-API-FedRAMP_Plan_of_Action_and_Milestones.zip](https://github.com/GSA/fedramp-automation/files/9529930/OSCAL-API-FedRAMP_Plan_of_Action_and_Milestones.zip)

**Comment by danielnaab** [comment]
We can't reproduce this - I see two instances of this error, both of which lack a `related-observation`. Can you confirm that the errors under the "Learn more" link all have `related-observation`s?

![Image](https://user-images.githubusercontent.com/136512/200063804-f12cd9f5-7628-4182-8cc6-6e4a46891011.png)


![Image](https://user-images.githubusercontent.com/136512/200063871-63c3e1d3-834f-4930-b0cc-ec3a1581c769.png)



![Image](https://user-images.githubusercontent.com/136512/200063899-f2875a03-ced1-4c39-b987-267158ad4158.png)
