### ISSUE TITLE
SSP Resource not read by validator

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#256]
# Describe the bug
SSP is being passed into the validator as a resource within POA&M, but it is not reading the content
{A clear and concise description of what the bug is.}

# Who is the bug affecting?
Telos

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))
1.0.4
# What is affected by this bug?
Validation with UI validator
{Describe the impact the bug is having.}

# When does this occur?
Validation
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}

1. Create a POAM json that includes SSP as a back-matter resource
![SSP Resource](https://user-images.githubusercontent.com/104856767/188723480-47a4cb2f-ae53-4a51-a29a-2b7d6e04b570.png)
2. Load the json into the UI validator
3. Note error
![Image20220906141944](https://user-images.githubusercontent.com/104856767/188723836-e4313fbf-db72-492a-9ba1-4589f3d22e32.jpg)

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by markXLIX** [comment]
The child of oscal:poam-item is oscal:related-observation.
https://pages.nist.gov/OSCAL/reference/latest/plan-of-action-and-milestones/xml-reference/#/plan-of-action-and-milestones/poam-item/related-observation

The code snippet provided shows oscal:related-observations.

**Comment by danielnaab** [comment]
This should be fixed, could you confirm?
