### ISSUE TITLE
Validator yields error when SSP attached to POA&M Back Matter

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#262]
# Describe the bug
When an SSP is attached to a POA&M via back-matter resource, the validator still yields an error stating that an SSP must be declared as a resource.
{A clear and concise description of what the bug is.}

# Who is the bug affecting?
Telos

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

# What is affected by this bug?
Validation
{Describe the impact the bug is having.}

# When does this occur?
When Validating POA&M's 
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}

1. Create an SSP and POA&M file
2. Include the SSP as a resource in POA&M back matter
3. Run POA&M through validator
4. Note errors

{If applicable, add screenshots to help explain your problem.}
"import-ssp":{ "href":"#c9db1389-df23-4118-b1a2-078d33734880"},
...
  "back-matter":{
            "resources":[ "uuid":"c9db1389-df23-4118-b1a2-078d33734880", "title":"OSCAL-API FedRAMP System Security Plan", 
                  "props":["name":"type", "ns":"https://fedramp.gov/ns/oscal", "value":"ssp" "rlinks":[ "href":"deliverable/OSCAL-API_OSCAL-export_20220923.xml"
![image](https://user-images.githubusercontent.com/104856767/192848553-212443ce-6309-4ec5-9ef0-934b2c153180.png)
![image](https://user-images.githubusercontent.com/104856767/192848614-b37e7137-181b-4baa-9010-f4c731a8a227.png)

# Expected behavior (i.e. solution)
SSP is accepted as back matter resource.
{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by markXLIX** [comment]
The problem here is the value of the prop/@value.  The Guide is incorrect to use 'ssp'.  It should be 'system-security-plan' as shown in the fedramp_values document (linked below).

This will need to be updated by FedRAMP documention.

https://github.com/18F/fedramp-automation/blob/d61203607904f0dfc012af2dcd63d766d9a31586/src/content/resources/xml/fedramp_values.xml#L524

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
