### ISSUE TITLE
typo: "800-54 Revision 4"

### ISSUE THREAD

**Issue by openprivacy** [GSA/fedramp-automation#263]
https://github.com/GSA/fedramp-automation/blob/9fd68f126dd67a0b3e24923a4adaf95886f5544f/src/validations/rules/ssp.sch#L1223

Should be "800-53 Revision 4"

Noting that the reference to "17 ... control families" exists as Program Management (PM) is is not represented in any baseline.

**Comment by GaryGapinski** [comment]
Thanks for the correction! It warrants an issue in the downstream working repository to make the comments independent of NIST SP 800-53 revision. The assertion tests are version agnostic.

See https://github.com/18F/fedramp-automation/issues/703.
