### ISSUE TITLE
Validator requires "agreement" not "isa-agreement"

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#264]
# Describe the bug
The validator throws an error when system-implementation component="interconnection" link rel="isa-agreement" It must be updated to accept this correct value.
![image](https://user-images.githubusercontent.com/104856767/195913916-72563054-56a8-4d31-8dbf-0aa3fde8a80d.png)

{A clear and concise description of what the bug is.}

# Who is the bug affecting?
Telos
# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

# What is affected by this bug?
UI Validator
{Describe the impact the bug is having.}

# When does this occur?
During Validation.
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}
1. Include isa-agreement in SSP
2. Run through validator and note errors

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)
Validator accepts link rel="isa-agreement"
{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by markXLIX** [comment]
This is an error in the validation as well as in the Guide.

Validation is being corrected ([see 714 in 18F/fedramp-automation](https://github.com/18F/fedramp-automation/issues/714)) 

Guide Section 4.20 Representation must be fixed:
![image](https://user-images.githubusercontent.com/97246567/197570578-5c40bf53-e741-434e-8aa1-5fdcfc003bec.png)

**Comment by danielnaab** [comment]
Should be fixed.
