### ISSUE TITLE
prop name="purpose" required in wrong section in validator

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#265]
# Describe the bug
The validator throws an error when prop name=”purpose” is omitted from the inventory-item parent tag.
![image](https://user-images.githubusercontent.com/104856767/197024037-a14c841c-bce7-4496-9d03-d73a9300a27b.png)
Per NIST requirements, prop name="purpose" is contained in the component tag.
![image](https://user-images.githubusercontent.com/104856767/197024843-d5e6b07a-2d4b-40a7-b545-d2572a548a22.png)

{A clear and concise description of what the bug is.}

# Who is the bug affecting?
Telos
# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))
1.0.4
# What is affected by this bug?
Validation
{Describe the impact the bug is having.}

# When does this occur?
When Validating
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}

1. Create an SSP with prop name="purpose" under component tag.
2. Attempt UI validation
3. Note errors

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)
No error when included in component, error when omitted from component if required by FedRAMP.
Not only is it in the wrong location, but it is a <purpose> tag, not a purpose prop
{A clear and concise description of what you expected to happen.}

# Other Comments
FedRAMP SSP guide does not include prop name="purpose" in inventory-item or component.
![image](https://user-images.githubusercontent.com/104856767/197025306-e243afc5-e195-41cc-92be-aafda1bdf80e.png)
![image](https://user-images.githubusercontent.com/104856767/197025328-98daeb8a-8809-43b2-9348-d748aa324fcf.png)

{Add any other context about the problem here.}

**Comment by markXLIX** [comment]
These validations for inventory-item will be removed as they are not mentioned in the Guide.  The SSP Guide does not state a requirement for component/purpose.  NIST OSCAL allows zero or one instances of purpose as a child of component.  

No further validation is required beyond OSCAL Schema validation.

Please see [https://github.com/18F/fedramp-automation/issues/715](https://github.com/18F/fedramp-automation/issues/715) for correction.

**Comment by danielnaab** [comment]
Still need to remove superfluous diagnostic message
