### ISSUE TITLE
Validator should not require a <role-id> tag in <system-implementation> <user>

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#266]
# Describe the bug
There is currently validation test that checks for a <role-id> tag within <system-implementation><user>.
![image](https://user-images.githubusercontent.com/104856767/197025999-123baaf8-50b1-40c1-b565-173788400b41.png)
![image](https://user-images.githubusercontent.com/104856767/197026017-0067e243-8c0e-40ab-9045-f0386e0fd82c.png)
This raises challenges, as not every frontend user is going to be responsible for one of the FedRAMP required roles. This could be resolved by defining a blanket role that could be assumed by all users that are not assigned one of those organizationally-defined roles.
This does exist in NIST’s documentation, but it is not required for this reason.
![image](https://user-images.githubusercontent.com/104856767/197026124-71373269-7d5c-4c57-90ef-5504d2de6b4e.png)

{A clear and concise description of what the bug is.}

# Who is the bug affecting?
Telos
# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

# What is affected by this bug?
Validation
{Describe the impact the bug is having.}

# When does this occur?
During Validation
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}

1. Create SSP without role-id tag in system-implementation user
2. Run through UI validator
3. Note errors

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)
role-id should not be required and yield no error.
{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by markXLIX** [comment]
The intent here appears to be to itemize roles within the Personnel Roles and Privileges.  Thus users without a role should not be included.

This likely requires more description and explanation by the FedRAMP Documentation for clarity.

**Comment by telosBA** [comment]
This could work, except NIST requires at least one user to be included in the ssp. 
![image](https://user-images.githubusercontent.com/104856767/198079710-be13c3bd-abd0-4339-8d6b-c783ee303e8a.png)

This would not be an issue if role-id was not required, as NIST indicates in its cardinality for role-id.

**Comment by volpet2014** [comment]
Added @Rene2mt for addressing in Rev 4/5 documentation updates.

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
