### ISSUE TITLE
LI-SAAS Baseline Control Implementation

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#267]
* **This is a ...**
  - [x] **concern** - I think something needs to be different.
  - [x] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [x] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [x] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier
![LI-SAAS](https://user-images.githubusercontent.com/104856767/197030695-daa072c1-f75b-4fb3-a6ac-d728b70b7831.png)

* **What is your feedback?**
Are users supposed to fill out the parent control or all sub statements? As the parent statement does not contain any details, how would they address this?
* **Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)** If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

* **What action would you like to see from the FedRAMP PMO?**
Address where details are supposed to be included (parent control or sub-statement).

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by volpet2014** [comment]
If the parent statement does not contain any details then users do not need to fill out the parent control.  However, any parent control that exists without a requirement has sub-requirements thus requiring sub-statements.  Sub statements should be included in this case.
