### ISSUE TITLE
Upgrade saxon-js version (source: 18F/fedramp-automation: 707)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#268]
Original issue: https://github.com/18F/fedramp-automation/issues/707

Upgrade saxon-js to latest version.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - check in with Wes on what we could do here
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by danielnaab** [comment]
SaxonJS was updated to 2.4 in #366. The current latest is 2.5, which has a breaking bug. See here: https://saxonica.plan.io/issues/5749

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
