### ISSUE TITLE
SAR: Identified Vulnerabilities - 4.7.1, 4.7.2 (source: 18F/fedramp-automation: 663)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#272]
Original issue: https://github.com/18F/fedramp-automation/issues/663

**Extended Description**
As an ASAP Developer, in order to reduce time FedRAMP reviewers require to ensure all risk-metric fields are properly identified, I want to check the Discovery Scans and Identified Vulnerabilities of an OSCAL SAR.

**Preconditions**
[Ensure that Issue 662 is complete and correct](https://github.com/18F/fedramp-automation/pull/662).  It is possible only minor tweaks are required to complete these sections.

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- [ ] ADD CRITERIA AFTER REVIEW OF PRECONDITION

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
