### ISSUE TITLE
Create ADR for rev 4/5 tagging approach (source: 18F/fedramp-automation: 615)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#275]
Original issue: https://github.com/18F/fedramp-automation/issues/615

**Extended Description**
As a FedRAMP rule writer, I would like to be able to tag Schematron rules to their corresponding NIST RMF revision, and have them evaluated in the appropriate context.

**Acceptance Criteria**
- [x] Architectural decision record written with approach
- [ ] Optionally, one or more initial rules tagged with this approach
- [x] Optionally, integrated into UI

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. Additionally, support for Rev 4 digital authorization packages is not in scope for current work or future roadmap. I am closing this issue as not planned.
