### ISSUE TITLE
Schedule of SAP Test Plan - SAP Guide Section 4.15 (source: 18F/fedramp-automation: 610)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#276]
Original issue: https://github.com/18F/fedramp-automation/issues/610

**Extended Description**
- As an ASAP developer, in order to provide FedRAMP reviewers appropriate indications regarding SAP Test Plan Schedules, I want to confirm correct elements and values for the SAP testing schedule.

**Preconditions**
Blocked:  See [https://github.com/GSA/fedramp-automation-guides/issues/34](https://github.com/GSA/fedramp-automation-guides/issues/34)

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- [ ] Check if at least one task element occurs with the attribute type of 'action'.
- [ ] Provide count of all task elements in the assessment-plan
- [ ] A task element must have a timing element child

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
