### ISSUE TITLE
Databases Slated for Testing in SAP (source: 18F/fedramp-automation: 576)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#280]
Original issue: https://github.com/18F/fedramp-automation/issues/576

**NOTES**
This change is deferred until progress is made on the SAP Guide.  There are too many unknowns within this section to support the decisions made here.

See [https://github.com/GSA/fedramp-automation-guides/issues/32](https://github.com/GSA/fedramp-automation-guides/issues/32) before continuing work.  Reevaluate all changes made in the linked branch.

**Extended Description**
As an ASAP developer, in order to identify assets that have a web interface, I would like to compare the SAP web tests with available SSP targets.

**Acceptance Criteria**
- [x] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [x] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [x] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [x] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- [x] Tests which target the SSP inventory data that identify database assets.
- [x] If SSP does not exist or matching SSP inventory data does not exist, SAP local definitions are examined for targeting by SAP database assets.
- [x] Every database (SSP or SAP) has a matching SAP task

**Story Tasks**
- [x] Tasks…

**Definition of Done**
 - [x] Acceptance criteria met
 - [x] Unit test coverage of our code > 95%
 - [x] Automated code quality checks passed
 - [x] Security reviewed and reported
 - [x] Reviewed against plain language guidelines
 - [x] Code must be self-documenting
 - [x] No local tech debt
 - [x] Load/performance tests passed – needs to be created/automated
 - [x] Documentation updated
 - [x] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
