### ISSUE TITLE
Refactor Schematron for use with SchXslt (source: 18F/fedramp-automation: 545)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#281]
Original issue: https://github.com/18F/fedramp-automation/issues/545

**Extended Description**
- This is required if SchXslt (see #529) is to be used.

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).

**Story Tasks**
- [ ] Refactor existing Schematron code so that all  Schematron variables are unique within the schema.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
