### ISSUE TITLE
Multi-document archive (source: 18F/fedramp-automation: 515)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#282]
Original issue: https://github.com/18F/fedramp-automation/issues/515

**Extended Description**
As a stakeholder, I would like to bundle my FedRAMP OSCAL documents in an archive, so I can cross-reference them and validate them as a group.

See multi-document rules ADR: https://github.com/18F/fedramp-automation/blob/master/src/validations/docs/adr/0009-multi-document-rules.md

**Preconditions**
- Multi-document rule writing approach determined.

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- More acceptance criteria…

**Story Tasks**
- [ ] Tasks…

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
