### ISSUE TITLE
Remove non-essential XSLT from Schematron (source: 18F/fedramp-automation: 503)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#283]
Original issue: https://github.com/18F/fedramp-automation/issues/503

**Extended Description**
- As a 10x ASAP developer, in order to provide clean Schematron code, I want all non-essential XSLT constructs removed from `ssp.sch`.

**Acceptance Criteria**
- [x] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [x] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [x] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- [x] Non-essential XSLT code is refactored into pure Schematron.
- [x] Essential XSLT code is minimized and highlighted within the code as anomalous.

**Story Tasks**
- [x] Identify non-essential XSLT code.
- [x] Refactor non-essential XSLT code.
- [x] Minimize and highlight essential XSLT code.
- [ ] Test transpiled Schematron.
- [ ] Profile transpiled Schematron.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
