### ISSUE TITLE
Review, Correct, and Validate documentation attributes for Assertions (source: 18F/fedramp-automation: 450)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#287]
Original issue: https://github.com/18F/fedramp-automation/issues/450

**Extended Description**
- As an ASAP Developer, in order to clearly identify the source of all assertions, I want to review and categorize all assertions without doc:* or feddoc:* attributes.

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- [ ] All assertions have attributes indicating the location of supporting documentation for the creation of the assertion.
- [ ] sch.sch is updated to test that each assertion contains at least one of the attributes used for indicating the location of supporting documentation.

**Story Tasks**
- [ ] Review all assertions that are missing a documentation attribute.
- [ ] Add correct documentation attributes where necessary
- [ ] Change the test for documentation attributes to ensure at least one of each is on every assertion.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Per [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) we are not going to use the Schematron validation approach, so I am going to close this issue as not planned.
