### ISSUE TITLE
Design How UI Shows Validation Messaging (source: 18F/fedramp-automation: 201)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#302]
Original issue: https://github.com/18F/fedramp-automation/issues/201

**Extended Description**

This is a spike for 18F#166.

As a 10x ASAP user, to understand the validations at the right level of detail, I want to be able to customize the amount of detail I see for validation errors, drilling down into technical details when I choose to (for domain specific security requirements to actual OSCAL data and syntax error explanations).

NOTE: At this time focus on tool developer and reviewer personas. The default validation messaging should be that of a reviewer (sch:assert default messages). Tool developers, and additional personas, should be specified as detail output that a user can opt-in to see (sch:diagnostics).

**Preconditions**
- N/A

**Acceptance Critera**
- [ ] Design an approach does not require the use to specifically filter for their own persona using the updated validation messaging from 18F#189 and presenting in the UI.

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [ ] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [ ] Code quality checks passed - Enable html tidy with XML code standards as part of the build (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing
 - [ ] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [ ] Source code merged - Code that’s demoed must be in source control and merged
 - [ ] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [ ] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [ ] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [ ] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Code refactored for clarity - Code must be clean, self-documenting
 - [ ] No local design debt
 - [ ] Load/performance tests passed - test data needed - saxon instrumentation
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by aj-stein-gsa** [comment]
We are not going to move forward with the current web UI approach, so I will close out this issue for now. For those who reported this issue or are following it, follow [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) for more details.
