### ISSUE TITLE
Design Spike: Document Validation Before Validation Rules (source: 18F/fedramp-automation: 169)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#303]
Original issue: https://github.com/18F/fedramp-automation/issues/169

**Extended Description**

As a 10x ASAP developer, to ensure any persona that is using the tool does not receive hard to understand errors or overwhelming technical output in a web browser, I would like to ensure any uploaded OSCAL XML document is validate with its XML schema.

(NOTE: Dan, this is converted from your backlog note: "Validate XSD in UI")

**Preconditions**
- N/A

**Acceptance Critera**
- [ ] A spike effort to develop MVP of this feature in code or a mockup showing how it should work

**Story Tasks**
- [ ] A short video showing how it would work and how it behaves 1) with a valid document and 2) without a valid document
- [ ] A summary comment below that indicates:
  - [ ] Pros
  - [ ] Cons
  - [ ] Estimated level of effort or risks in feature complete implementation of this in a follow-on story

**Definition of Done**
 - [ ] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [ ] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [ ] Code quality checks passed - Enable html tidy with XML code standards as part of the build (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing
 - [ ] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [ ] Source code merged - Code that’s demoed must be in source control and merged
 - [ ] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [ ] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [ ] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [ ] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Code refactored for clarity - Code must be clean, self-documenting
 - [ ] No local design debt
 - [ ] Load/performance tests passed - test data needed - saxon instrumentation
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices

**Comment by danielnaab** [comment]
I'm not aware of a compliant XML Schema validator that will run in-browser, but I am moving this issue to the backlog to be considered at a future point.

**Comment by aj-stein-gsa** [comment]
We are not going to move forward with the current web UI approach, so I will close out this issue for now.
