### ISSUE TITLE
Add XML, JSON, and YAML media types to `fedramp_values.xml` (source: 18F/fedramp-automation: 716)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#308]
Original issue: https://github.com/18F/fedramp-automation/issues/716

**Extended Description**
- Add missing media types for XML and JSON

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).

**Story Tasks**
- Update the document **[`src/content/resources/xml/fedramp_values.xml`](https://github.com/18F/fedramp-automation/blob/master/src/content/resources/xml/fedramp_values.xml)**.
- Format and indent as initial, separate commit (document has mixed 3- and 4-character indents).
- Add additional media types to end of `<value-set name="media-type">` `allowed-values` stanza.
- Add media type `application/xml`.
- Add media type `text/xml` (see [RFC 7303](https://www.rfc-editor.org/rfc/rfc7303.html) — both are allowed, `application/xml` is recommended).
- Add media type `application/json`.
- Add media type `application/yaml` (see [draft-ietf-httpapi-yaml-mediatypes-03](https://www.ietf.org/archive/id/draft-ietf-httpapi-yaml-mediatypes-03.html) which was recently in WG Last Call).
- Update the document metadata.

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by volpet2014** [comment]
Completed via PR 368.
