### ISSUE TITLE
SAR - replace "report" with "results" (source: 18F/fedramp-automation: 693)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#316]
Original issue: https://github.com/18F/fedramp-automation/issues/693

# Description
SAR is, according to the OSCAL team, "Security Assessment Results" - not "Security Assessment Report."

## Acceptance criteria
- [ ] Correct the references through the repository

**Comment by aj-stein-gsa** [comment]
We are not going to move forward with the current web UI approach, so I will close out this issue for now. For those who reported this issue or are following it, follow [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) for more details.
