### ISSUE TITLE
Initial replacement for Java UUID function. (source: 18F/fedramp-automation: 642)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#321]
Original issue: https://github.com/18F/fedramp-automation/pull/642

Note that there is inadequate seeding which requires correction.

**Comment by GaryGapinski** [comment]
This should also await disposition of usnistgov/OSCAL/issues/1416.

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) we will not advance Schematron-based tooling and this UUID concern will no longer be in scope. I am closing this issue as not planned.
