### ISSUE TITLE
Document Sensitivity Labels

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#34]
# Action Item

**This is a ...**
  - [ ] **enhancement** - Something could be better.

**This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON Format)
  - [ ] the **FedRAMP SSP OSCAL Template** (XML Format)

## Describe the problem or enhancement

Currently the ability to indicate a document label, such as "Controlled Unclassified Information (CUI)", is handled as a FedRAMP Extension to OSCAL.
The NIST OSCAL Team is considering adding the syntax for this to the core OSCAL syntax,. Once that happens, FedRAMP's OSCAL Guide, Registry, and templates will need to be updated to reflect this change.

## Goals:

Ensure FedRAMP's OSCAL materials to reflect core OSCAL syntax for document labeling, when NIST publishes this change as part of the OSCAL [1.0.0-milestone3 Release](https://github.com/usnistgov/OSCAL/releases) later this year.

## Dependencies:

usnistgov/OSCAL#600

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

## Other Comments

None.

**Comment by ohsh6o** [comment]
Per [the provided example SSP currently in this repository](https://github.com/18F/fedramp-automation/blob/master/templates/ssp/xml/FedRAMP-SSP-OSCAL-Template.xml) as well usnistgov/OSCAL#600 and usnistgov/OSCAL#619 indicate this is cleared up for now.
