### ISSUE TITLE
XSpec clarity in web documentation (source: 18F/fedramp-automation: 516)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#343]
Original issue: https://github.com/18F/fedramp-automation/issues/516

**Extended Description**
As a user, I would like to read clear XSpec textual representations in the web documentation.

Context: The web documentation currently assembles a scenario description by concatenating each parent into a single string. Some of the existing rules read well in this format, while some are awkward. For example:
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/136512/170533942-d6ded557-0ec6-40fc-9266-ae7191655f43.png">

This work could include updating scenario descriptions in the XSpec, or altering the presentation in the web documentation to be more appropriate for the content.

**Acceptance Criteria**
- [ ] XSpec descriptions read clearly in the web documentation

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), XSpec will not be used any more to test with the previous constraint architecture and soon be removed.
