### ISSUE TITLE
Remove 10x Github artifacts from repository (source: 18F/fedramp-automation: 572)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#346]
Original issue: https://github.com/18F/fedramp-automation/issues/572

**Extended Description**
As a FedRAMP engineer, I would like 10x ASAP workflow-related items to be removed from the git repository.

Context: things like Github Issue templates were created for the 10x team. Delete, or modify, these things to be appropriate for long-term FedRAMP usage.

**Acceptance Criteria**
- [ ] 10x-specific things removed from git repository
- [ ] Merged to GSA/fedramp-automation

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - check in with Wes on what we could do here
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
It seems much of this is planned in a direct or indirect manner as part of [post-ADR-7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) work starting in #738. I will close this for now and use that cross-link to double check for any 10x artifacts that may remain.
