### ISSUE TITLE
Minimize CSS bundle size (source: 18F/fedramp-automation: 520)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#347]
Original issue: https://github.com/18F/fedramp-automation/issues/520

**Extended Description**
As a user, I want the site to load quickly. Minimize the currently bloated CSS file.

Prunecss is an option.

**Acceptance Criteria**
- [ ] CSS size in minimized

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%  
 - [ ] Automated code quality checks passed 
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by david-waltermire-nist** [comment]
Closing this for now. This can be reopened later if needed.
