### ISSUE TITLE
OSCAL File Fragments - System Inventory

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#35]
# Action Item

**This is a ...**
  - [ ] **enhancement** - Something could be better.

**This relates to ...**
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans** (PDF)
  - [ ] **General/Overall**

## Describe the problem or enhancement

Currently OSCAL is designed to be complete. This means it is difficult to just provide OSCAL-based inventory data outside the context of a complete OSCAL-based SSP file.

NIST is currently working on an approach that provides OSCAL content authors the ability to represent just a portion of an OSCAL file, while still enforcing OSCAL syntax and allowing format conversion.

Once NIST has solidified their approach to OSCAL file fragments, the FedRAMP guide will be updated.

## Goals:

Establish clear guidance for FedRAMP stakeholders to extract OSCAL-based inventory information from a larger OSCAL-based SSP, such that the inventory representation is standardized across FedRAMP stakeholders while retaining OSCAL compliance.

Ensure FedRAMP's guidance updated when NIST publishes this change as part of the OSCAL [1.0.0-milestone3 Release](https://github.com/usnistgov/OSCAL/releases) later this year.

## Dependencies:

usnistgov/OSCAL#590

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

## Other Comments

None.

**Comment by ohsh6o** [comment]
Will definitely want to review and add for upcoming discussion around usnistgov/OSCAL#903 and usnistgov/OSCAL#904.

**Comment by brian-ruf** [comment]
This can now be accomplished by including the system inventory as a `local-definition` in the POA&M model.

**Comment by ohsh6o** [comment]
@brian-ruf, glad to see you are still lurking! (Sorry I missed the assignments before updating.) I know `local-definition` supports it in models other than `system-security-plan`, but I suspect some want to be able to perform inventory declaration without embedding it in the SSP as well. That use case is definitely useful and welcome.

See usnistgov/OSCAL#903.

**Comment by volpet2014** [comment]
Collaborated with NIST on this issue.  Various approaches were discussed.  No long term solution currently exist.  NIST is continuing to look at potential solutions.  Monitoring usnistgov/OSCAL#903 for resolution.
