### ISSUE TITLE
UI Validator broken links

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#357]
# Describe the bug
A bug exists within the UI validator. When a validation test is run, the two fatal checks in the section of “SSP Template 15” have a broken button. When you click “View Examples” on either of the following two errors, the site displays a white screen that you cannot recover from.
![image](https://user-images.githubusercontent.com/104856767/199777806-ef9f3d52-4163-4029-be9d-f54d706a6199.png)
This can be easily recreated using these steps:
1.	Launch the UI validator ([FedRAMP Validations (cloud.gov)](https://federalist-2372d2fd-fc94-42fe-bcc7-a8af4f664a51.app.cloud.gov/site/18f/fedramp-automation/#/documents))
2.	Select “FedRAMP-SSP-OSCAL-Template.xml
3.	Select “FedRAMP SSP Template” from the “Select a view”
4.	Filter the results by “Fatal”
5.	Enter Section 13
6.	Select “View Examples”

# Who is the bug affecting?
Telos
# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

# What is affected by this bug?
Viewing error examples
{Describe the impact the bug is having.}

# When does this occur?
After UI validation, upon clicking "View Examples" under the aforementioned fatal errors.
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

1. Create an SSP that yields the noted errors upon validation
2. Run the SSP through the UI Validator
3. Attempt to click "View Examples" under noted errors

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)
Link works
{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by danielnaab** [comment]
Thanks for the bug report. Fixed in #391
