### ISSUE TITLE
The <base64> tag should not be required in every resource

### ISSUE THREAD

**Issue by telosBA** [GSA/fedramp-automation#359]
* **This is a ...**
  - [x] **concern** - I think something needs to be different.
  - [ ] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [x] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier
UI Validator

* **What is your feedback?**
NIST suggests that this should be optional, and interchangeable with <rlink>. Here is the error that is thrown when it is omitted from a resource element:
![image](https://user-images.githubusercontent.com/104856767/199780497-fcd3d81f-cbcd-43eb-be98-3a66d55f352e.png)
The test for <base64> should still be supported, but the requirement should be satisfied if <rlink> is properly implemented.
* **Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)** If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

* **What action would you like to see from the FedRAMP PMO?**
Remove requirement for base64 tag in resources.

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by GaryGapinski** [comment]
I concur: base64 embedding is not a good idea.

**Comment by markXLIX** [comment]
pg 49, Section 6.1 Attachments of the Guide to OSCAL-based FedRAMP Security System Plans indicates that either a base64 or rlink is required as a child of each back-matter/resource.

The assertion 'resource-has-base64' in the ssp.sch should be reevaluated in light of that.

**Comment by Telos-sa** [comment]
Error still exists in the cli validator for every attachment.  Attached evidence.  
[Validations.zip](https://github.com/GSA/fedramp-automation/files/11520315/Validations.zip)

**Comment by dimitri-zhurkin-vitg** [comment]
In rev 5 SSP, changed resource-has-base64 severity from warning to information.
