### ISSUE TITLE
Test for matching import-*/@href value with a resource/@uuid value

### ISSUE THREAD

**Issue by markXLIX** [GSA/fedramp-automation#365]
Extended Description

As a developer, to add clarity where import-* may fail when handling an internal reference to resource, I would like to create a test for verifying matching values of import-*/@href and a back-matter/resource/@uuid value.

Preconditions

N/A

Acceptance Criteria

[ ] assert/diagnostic combo for ssp, sap, sar, poam for import-*/@href with values starting with '#' test whether a match exists with a back-matter/resource//@uuid
[ ] xspec tests for each
[ ] passes automated code testing
[ ] code reviewed

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
