### ISSUE TITLE
Change set-param to set

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#37]
# Action Item

**This is a ...**
  - [ ] **fix** - Something needs to be different.

**This relates to ...**
  - [x] the **Guide to OSCAL-based FedRAMP System Security Plans** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON Format)
  - [ ] the **FedRAMP SSP OSCAL Template** (XML Format)

## Describe the problem or enhancement

NIST changes the syntax for setting parameters in profile from ```set-param``` to simply ```set```. Currently the SSP syntax still uses ```set-param```. 

NIST intends to update the SSP syntax to match the profile syntax. This will require changes to the FedRAMP OSCAL guide and templates.

## Goals:

Update the OSCAL-based FedRAMP guide and templates to reflect NIST's syntax change, when they publish it as part of the OSCAL [1.0.0-milestone3 Release](https://github.com/usnistgov/OSCAL/releases) later this year.

## Dependencies:

usnistgov/oscal#568

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

## Other Comments

None.

**Comment by brianrufgsa** [comment]
Per the comment in usnistgov/oscal#609, it appears NIST may be changing ```set-param``` to ```set-parameter``` instead of simply ```set```.

**Comment by ohsh6o** [comment]
It would appear the necessary code changes are stabilized, but will definitely need to review these changes as they pertain to the FedRAMP OSCAL Guidebooks.

**Comment by ohsh6o** [comment]
I reviewed and updated the docs. Will update and close this issue when draft revisions are published.
