### ISSUE TITLE
Reading HTML code within Multi-line Markup and strings

### ISSUE THREAD

**Issue by TelosPO** [GSA/fedramp-automation#375]
**Extended Description**
I want to validate data that is in a table structure for Multi-line markup and strings are there any restrictions in the validator in reading html table structure.

**Preconditions**
- Preconditions…

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- More acceptance criteria…
HTML recognized 
**Story Tasks**
- [ ] Tasks…

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [X ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by volpet2014** [comment]
Multi-line markup and strings as a limited subset in OSCAL is supported.  See  https://pages.nist.gov/OSCAL/reference/datatypes/#tables for more information.  If the issue is not resolvable via this guidance, please open a new issue and provide additional detail.
