### ISSUE TITLE
Risk associated with multiple POAMs

### ISSUE THREAD

**Issue by TelosPO** [GSA/fedramp-automation#381]
* **This is a ...**
  - [ ] **concern** - I think something needs to be different.
  - [X ] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [X] **General/Overall**
  - [ ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

* **What is your feedback?**
If there are multiple POAM that share a Risk but there are different due dates for the respective POAMs what should the expected remediation date of the risk?
* **Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)** If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

* **What action would you like to see from the FedRAMP PMO?**

Clarification on desired result

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by volpet2014** [comment]
@volpet2014 forwarded question on to review team POA&M SME.   Awaiting response.

**Comment by volpet2014** [comment]
Per PMO POAM SME:
There are two approaches that are acceptable for FedRAMP. 

1. The CSP can retain one POA&M based on the vuln ID and add all affected assets to the asset impacted cell. The original detection date for this singular POA&M would be the recorded from the earliest found vulnerability of this type.

2. The CSP can create POA&M's based on the original detection dates. With this method there will be multiple POA&M's for the same Vuln ID, but each POA&M will have its own unique POA&M ID and different original detection dates to differentiate them.
