### ISSUE TITLE
Rules for managing the UUID creation and updates

### ISSUE THREAD

**Issue by vmangat** [GSA/fedramp-automation#384]
* **This is a ...**
  - [x ] **concern** - I think something needs to be different.
  - [ ] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ ] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ x] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ ] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

* **What is your feedback?**
We need a consolidated approach for guidance on when the UUID for documents and objects should be changed or kept as it

* **Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)** If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

* **What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))**

* **What action would you like to see from the FedRAMP PMO?**

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by vmangat** [comment]
Providing a high level framework to help with the thought process of managing UUIDs accross all the artifacts.  This is just one proposed view, from our tooling perspective.

I have provided the same information to the issue logged in NIST/OSCAL git. This may need a discussion and happy to participate in a call as desired.

![image](https://user-images.githubusercontent.com/98432030/214692298-33269391-bc8e-442f-8692-63cffae21b0c.png)

**Comment by vmangat** [comment]
we are preparing something similar for each object in every OSCAL artifact. If the community likes this, we can share more as our analysis comes available.

**Comment by sunstonesecure-robert** [comment]
I think in terms of "object class" (or interface) vs "instance"...a UUID could/should be for both...but class/interface UUIDs will change much less frequently than highly volatile object instances.  

I *think* this aligns with the [documentation here](https://pages.nist.gov/OSCAL/concepts/layer/overview/#use-of-version-4-uuids)

not sure how this aligns with the diagram above... I like it :)  just not sure I understand it ;)

**Comment by vitggsa** [comment]
FedRAMP is looking to the community for refinement of our process.   In a previous Data Bites session we layed out some basic things we are planning doing but this will need more refinement over time.   FedRAMP is planning on standing up a working group for early adopters separate from Data Bites (CSP Engineering teams, GRC tool vendors, etc.) and this topic is high on the list as an initial working group item to tackle.  Note: We are currently working on an approach which doesn't totally depend on UUID changes to determine changes in OSCAL artifacts.

**Comment by volpet2014** [comment]
A document clarification from NIST is pending.  Will hold on resolution until that clarification exists.

**Comment by Telos-sa** [comment]
Recommend also reviewing how the UUIDs are generated for the nested objects.  We are leveraging method 5 generation so we can "lock-in" the statement UUIDs for the controls, so they only change when the statement itself changes. 

However, we need to understand what would be a security relevant change for specific areas to know which props to include in the method5 identification.  

For instance Asset inventory.  What props would require a UUID change, and trigger a review?  Would it be host name & IP, or if it is public vs private, virtual, testable....

**Comment by volpet2014** [comment]
The UUID was discussed in detail at a previous Data Bites session.   Following that session we had discussions with NIST on this topic and a made a decision (until the dust settles) for our initial review process that we are not planning on using UUID's to signal a review of specific content within an OSCAL document.   We are getting different approaches from different tool vendors with regard to this.
Note: We definitely agree with your approach to lock-in the statement UUIDs for controls.   
Our initial plan is to work at the data content level and compare contents of the elements directly between submissions of the document.  We are still working though this approach and it will evolve as we get more data into the Automation ecosystem after some analysis and review.  Although we realize that this is computationally intensive, we feel this "deep diff" approach will yield the way forward regarding UUIDs and what constitues a "significant change" in OSCAL and the ongoing discussion.
