### ISSUE TITLE
Add rev 5 ruleset to web documentation

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#385]
**Extended Description**
As a validations user, I would like the NIST RMF rev 5 ruleset to be browsable in the web documentation.

**Preconditions**
- The rev 5 ruleset exists, as supported by #353

**Acceptance Criteria**
- [ ] Both rev 4 and rev 5 rulesets are browsable in the web documentation

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 90% - needs automation story
 - [ ] Accessibility tests pass - needs automation story
 - [ ] Automated code quality checks pass
 - [ ] Security reviewed and reported - check in with Wes on what we could do here
 - [ ] Reviewed against plain language guidelines
 - [ ] Design QA passed
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by aj-stein-gsa** [comment]
We are not going to move forward with the current web UI approach, so I will close out this issue for now. For those who reported this issue or are following it, follow [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) for more details.
