### ISSUE TITLE
Prop value for pia or PIA for Privacy Impact Asseessment

### ISSUE THREAD

**Issue by ThomAPenn** [GSA/fedramp-automation#386]
# Describe the bug
A prop value should dictate whether the PIA,pia value.
{A clear and concise description of what the bug is.}
The schematron doesn't  allow for upper or lowercase when putting the value of pia within a prop, 
# Who is the bug affecting?

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)
Schematron

If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

# What is affected by this bug?
Schematron
{Describe the impact the bug is having.}

# When does this occur?
When there is a value of pia or PIA in a prop for Privacy Impact Asseessment
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?
```
<prop class="" name="type" ns="https://fedramp.gov/ns/oscal" uuid="" value="pia"> </prop>
```
{What are the steps to reproduce the behavior?}

1. put the above code 
```
<resource uuid="3f7ad2df1b0ded1c69c40e9ee54bcb46">
<title>privacy-impact-assessment</title>
<description>
<p>This is for testing purposes. Actual description will come in from the form used to enter the ssp information. As the schema mandates description of a certain length, this is used for now.</p>
</description>
<prop class="" name="type" ns="https://fedramp.gov/ns/oscal" uuid="" value="pia"> </prop>
<rlink href="https://c1securefedrampdev.servicenowservices.com/x_n1ll2_oscal_ssp_attachment.do?sys_id=96bdbdf81b37519069c40e9ee54bcb93" media-type=""> </rlink>
<base64 filename="privacy-impact-assessment attachment" media-type="application/vnd.ms-excel">00000000</base64>
</resource>
```
1. Validate.
1. Error is in the tags

{If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by volpet2014** [comment]
FedRAMP PMO is reviewing the requirement of schematron validation for the existence of a pia and considering removing the schematron rule that is throwing this error/warning.  Update on this forthcoming.

**Comment by volpet2014** [comment]
Rule has been removed from current Schematron ruleset.
