### ISSUE TITLE
sample-ssp.xsl has flawed Schematron xml-model PI

### ISSUE THREAD

**Issue by GaryGapinski** [GSA/fedramp-automation#387]
# Describe the bug

[This](https://github.com/GSA/fedramp-automation/blob/43685accaef96434d9ff59c4236ba0d25302c961/src/validations/rules/sample-ssp.xsl#L155) is incorrect. The syntax is missing `href=` and the target schema is incorrect.

# Who is the bug affecting?

Users of `sample-ssp.xsl`.

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

No.

# What version of OSCAL are you using?

1.0.4.

# What is affected by this bug?

`sample-ssp.xsl` produces invalid output.

# When does this occur?

Durably.

# How do we replicate the issue?

Use `sample-ssp.xsl` to produce an OSCAL SSP instance document.

# Expected behavior (i.e. solution)

The `xml-model` processing instruction in the output should be
```xm;
<?xml-model schematypens="http://purl.oclc.org/dsdl/schematron" title="FedRAMP SSP constraints" href="https://raw.githubusercontent.com/GSA/fedramp-automation/master/src/validations/rules/rev4/ssp.sch" phase="#ALL"?>
```

# Other Comments

See also https://github.com/usnistgov/oscal-cli/issues/109.

**Comment by volpet2014** [comment]
Does this address the stack dumps from OSCAL-CLI?  I am still getting them after I fixed the href= reference at the top of the sample I put in with oscal-cli/#109

**Comment by aj-stein-nist** [comment]
> Does this address the stack dumps from OSCAL-CLI? I am still getting them after I fixed the href= reference at the top of the sample I put in with oscal-cli/#109

I believe what @GaryGapinski is saying, he will correct me if I am wrong:
1. `<description />` is valid whether or not the `oscal-cli` complains
2.  the tool should be reviewed and a patch made
3. a workaround, although it is to workaround 1 until 2 arrives, would be to have filled out descriptions like `<description><p>Cute commentary</p></description>` as a workaround not a permanent fix in the content
