### ISSUE TITLE
@name Flag Syntax Updates

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#39]
# Action Item

**This is a ...**
  - [ ] **fix** - Something needs to be different.

**This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON Format)
  - [ ] the **FedRAMP SSP OSCAL Template** (XML Format)

## Describe the problem or enhancement

NIST is updated the @name flag in several places where a title field is better suited than an @name flag. This also addresses concerns where the @name flag was required, but of NCname data type, which could not accept spaces.

NIST is changing the @name flag to a title element for the following assemblies in the OSCAL syntax:
- authorized-privilege
- component
- information-type
- leveraged-authorization
- service

In relation to this, NIST is also adding an @id flag, and a title field to the ```protocol``` assembly, but is leaving the @name flag as-is.

## Goals:

Ensure the Guide, Registry, and templates are updated to reflect these syntax changes.

## Dependencies:

usnistgov/oscal#535

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

## Other Comments

None

**Comment by ohsh6o** [comment]
Will revisit later when updates occur with usnistgov/OSCAL#911.

**Comment by ohsh6o** [comment]
In preparation for 1.0.0 I reviewed the documentation and cleaned up the referenced issues in the docs. Having reviewed these issues and how usnistgov/OSCAL#911 is not directly applicable, will mark this one resolved when the document updates are published to the repo.
