### ISSUE TITLE
Issues with NodeJS version upgrade

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#397]
Please view the word format ticket to view the associated images in-line as it was written:
[FedRAMP Validator Make Issue (NodeJS Upgrade).docx](https://github.com/GSA/fedramp-automation/files/11066622/FedRAMP.Validator.Make.Issue.NodeJS.Upgrade.docx)

Our team has been working on building out a new instance of the validator tool. We are doing so to upgrade from the 18F branch to the more recent version, propping it up in a t2.large ec2 running the following OS:  

We replicated our old workflow (Used for 18F) for setting up this instance, using the exact same security groups, install tactics, etc. to support the new repo. When we encountered the requirement for a higher version of nodejs, we started having issues. Here are the broad strokes attempt at the node update, skipping over the obvious installs like make and python.

1.	Cloned https://github.com/GSA/fedramp-automation.git.
2.	Curled the correct version of node into vendor/:
a.	curl -O https://nodejs.org/dist/v18.15.0/node-v18.15.0.tar.gz
3.	This caused dependency issues, specifically with node. The install worked, and the path was linked, so it could be used. However, it threw these errors when running make all, or even checking node’s version:
 
Note: These are not recommended to be upgraded nor altered (https://stackoverflow.com/questions/59145051/glibc-2-27-not-found-ubuntu-16-04)
4.	Installed Node directly from source (Curled, untarred, linked, and built it from ISO)
 
Note: “make” takes hours for this download technique.
5.	This resulted in dozens of errors, primarily in missing modules. We managed to work our way through by individually npm installing all the dependencies as they appeared:
a.	Mkdirp
b.	npm-run-all
c.	tsup
d.	xml-formatter
e.	saxon-js
f.	highlight.js
g.	xslt3
h.	typescript
i.	vitest
j.	react
k.	vitest-mock-extended
l.	jsx jsx-elements
m.	jsx-runtime
n.	react-dom
o.	react-modal
p.	@types/react
q.	@types/react-modal
r.	@types/react-dom
s.	Classnames
t.	Reselect
u.	path-to-regexp
6.	After completing all installs suggested by the output, we still have the following errors left:
 
7.	To correct this, we have tried a few different installs and tested changes in the tsconfig file. We have not managed to resolve these errors.

Admittedly, we went a little too far down the rabbit hole of trying to make the alternate node installment method work by manually installing the npm dependencies. If we can start again, we’d be happy to, but there seems to be an issue with the interactions between the GSA/fedramp-automation repo and Node (V18.15) when installed OOTB.
Do you have any guidance on how you have built/upgraded to the newer validator builds that leverage the newest version of node?

**Comment by Telos-sa** [comment]
After some further testing, the "GLIBC" errors were unique to the AWS AMI we were using. Switching to the 2023 AWS linux instance avoids that particular error, but still throws dependency errors as shown in Step 5. It all begins with the "make all" command not being able to find the mkdirp module. If installed, we follow the trail of errors (mkdirp, npm-run-all, tsup, etc...) to the same end result. Any sort of guidance to the current instillation procedure would be very helpful.

I recommend reducing the required node version from 18.15 to 18.13, the stable version defaulted by a yum install of nodejs. This would likely eliminate the npm dependency errors, but I can't be sure with the hard version-restriction on the "make."

**Comment by Telos-sa** [comment]
Further testing indicates that the dependency issues are independent of the nodejs versioning. Using NVM, we simplified the process of manually overriding the default node version, but we still manually have to install the ~25 modules required by the make file. Do you have a list of npm dependencies that could be provided? We are still stalled out on the following errors, and have tried every dependency we could think of:
![image](https://user-images.githubusercontent.com/127163717/229566850-7af69331-66b0-49b2-8e58-a8a9ecba5eee.png)
Futhermore, the file being searched for the in the second error (../node_modules/saxon-js/package.json) does exist, but its path is not being resolved. Proof of file existence:
![image](https://user-images.githubusercontent.com/127163717/229567254-75eeee18-13a6-4fe4-93d1-152ca3df421d.png)
Any guidance on further npm dependencies or install procedure would be greatly appreciated.

**Comment by danielnaab** [comment]
If you're not aware, FedRAMP has a Cloud.gov Pages deployment available here: https://federalist-b6c4d61f-facd-4833-a4a9-554523a87147.sites.pages.cloud.gov/site/gsa/fedramp-automation/ This always represents the current state of the master branch.

With respect to node.js version, some effort was expended to ensure that the most recent LTS version of node.js is used, to limit the amount of upcoming dependency management FedRAMP will need to engage in the next couple years. So, I'm sorry that has created issues for you.

Assuming you have the correct version of node.js installed via `nvm`, you may avoid a complete `make all` using the build method used for the Cloud.gov Pages build (see https://github.com/GSA/fedramp-automation/blob/master/package.json#L8):

```bash
make init-repo
cd src/web
npm install
npm run build
```

**Comment by Telos-sa** [comment]
Thanks for the response! We do have the correct version of nodejs installed thanks to nvm, so that portion of my original ask is now irrelevant. I am familiar with the federalist validator, but I was previously using the 18F version (https://federalist-2372d2fd-fc94-42fe-bcc7-a8af4f664a51.sites.pages.cloud.gov/site/18f/fedramp-automation/#/documents), so that is very helpful. I am setting up a locally install to process client data.

I have followed your instructions for building without make all. I managed to avoid those build errors this way, but still encountered issues upon validation. The command runs as expected to begin with, then just stops:
![image](https://user-images.githubusercontent.com/127163717/229618681-5de11515-6a22-4b45-97dd-3cf2ca1e023e.png)
For contrast, here is an image of what a complete run looks like from a few months ago:
![image](https://user-images.githubusercontent.com/127163717/229618809-db58cc47-86df-4e17-8b4c-6903f2e67c71.png)
Any idea on what could contribute to this? I'm not sure what differences lie between the two make strategies, or if that affects the efficacy at all.

**Comment by Telos-sa** [comment]
Well, that second picture did not show up well. Lets try that again: 
![image](https://user-images.githubusercontent.com/127163717/229619710-b408ce33-7cad-4fd2-8a27-d38c3903a1cb.png)

**Comment by danielnaab** [comment]
Hello, thank you for the report on that. I created #406 to track that problem.

Note that in your screenshot, you are validating a JSON file, but the script only supports XML - so you will need to convert using the OSCAL JSON to XML transform first. Nonetheless, the script still has underlying issues preventing XML from validating correctly, as well.
