### ISSUE TITLE
Missing Objective Response Points (Compared to Security Test Procedures)

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#399]
# Action Item
Telos has begun working on the SAP and SAR models.  During our investigation we have identified 56 Assessment Procedures from the current SAP-AA FedRAMP High Security Test Case Procedures that are **NOT** included in the FedRAMP High Baseline profile Catalog Last modified on 2023-03-22. 

**This is a ...**
  - [ X ] **fix** - Something needs to be different.
  - [ X ] **enhancement** - Something could be better.
  - [ X ] **investigation** - Something needs to be investigated further.

**This relates to ...**
  - [ X ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ X ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ X ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ X ] **General/Overall**
  - [ X ] **Other**

NOTE: For issues related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

## Describe the problem or enhancement

Requesting review of the following Assessment Procedures from the SAP-AA FedRAMP High Security Test Case Procedures and either additional response points included in the next OSCAL baseline profile release, or instructions or details to confirm that these 56 assessment procedures are no longer required.  

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/13503/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/13503/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Assessment   Procedure
--
AC-4.1
AC-4.2
AC-12.a.1
AC-12.a.2
AU-4.1
AU-9.1
AU-9.2
AU-10.1
AU-10.2
AU-11.1
CA-8.1
CA-8.2
CM-4.1
CM-5.1
CM-5.2
CM-5.3
CM-5.4
CM-5.5
CM-5.6
CP-6.a
CP-6.b
CP-8.1
CP-8.2
CP-8.3
CP-10.2
IA-2.1
IA-3.1
IA-8.1
IR-3.1
IR-3.2
IR-5.1
IR-7.1
IR-7.2
MA-3.1
MA-3.2
MA-3.3
MA-6.1
MA-6.2
MA-6.3
MP-7.1
MP-7.2
PE-12.1
PE-13.1
PE-13.2
PE-18.1
SA-4.1
SA-12.1
SA-12.2
SC-5.1
SC-5.2
SC-5.3
SC-12.1
SC-12.2
SC-28.1
SC-28.2
SI-7.2

</body>

</html>

## Goals:

1) Updated Baseline profile catalog that matches the Manual process

or

2) Guidance on how to submit / handle / ignore the misalignment.  

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ X ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- [ X ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

## Other Comments

Will relate to the additional tickets submitted for misaligned response points, and new response points

**Comment by Rene2mt** [comment]
This issue has been resolved by PR https://github.com/GSA/fedramp-automation/pull/252 which is pending merge. Once this merge occurs, this issue should be resolved as it was related to mis-aligned ids in the profile and resolved-profile-catalog

**Comment by Telos-sa** [comment]
@Telos-sa will review the new baseline profiles and confirm that all of the objective response points that should be included are included.
