### ISSUE TITLE
`uuid-` missing in catalog/@id ; hence files no longer valid OSCAL after latest OSCAL changes

### ISSUE THREAD

**Issue by isimluk** [GSA/fedramp-automation#40]
Hello, 

It seems that some of the files here are no longer valid OSCAL (assuming latest head of https://github.com/usnistgov/OSCAL is correct). Not only set/set-param issues needs to be fixed.

It seems that `@id` parameter on the root element needs to be reformatted as well. Seems that `uuid-` prefix is missing.

I am getting following errors, when trying to validate GSA files:
```
./baselines/xml/FedRAMP_MODERATE-baseline-resolved-profile_catalog.xml:2: element catalog: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}catalog', attribute 'id': '7723d8ef-9667-4ae5-8316-0ce2d81a67d0' is not a valid value of the atomic type 'xs:NCName'.
./baselines/xml/FedRAMP_MODERATE-baseline-resolved-profile_catalog.xml fails to validate

./baselines/xml/FedRAMP_HIGH-baseline-resolved-profile_catalog.xml:2: element catalog: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}catalog', attribute 'id': '0a8a1cf0-d22d-4a80-9f57-08483cdd6f37' is not a valid value of the atomic type 'xs:NCName'.
./baselines/xml/FedRAMP_HIGH-baseline-resolved-profile_catalog.xml fails to validate

./baselines/xml/FedRAMP_LI-SaaS-baseline-resolved-profile_catalog.xml:2: element catalog: Schemas validity error : Element '{http://csrc.nist.gov/ns/oscal/1.0}catalog', attribute 'id': '8b898586-6ae4-4685-8e32-600755fe556b' is not a valid value of the atomic type 'xs:NCName'.
./baselines/xml/FedRAMP_LI-SaaS-baseline-resolved-profile_catalog.xml fails to validate
```

### Reproducer
I used my [own version of oscalkit](https://github.com/docker/oscalkit/pull/88), as that's easiest to use:
```
   for f in `find | grep '\.xml$'`; do oscalkit validate $f; done
```
Nevertheless, the errors can be reproduced using any XSD validator with latest [schemafiles from oscal](https://github.com/usnistgov/OSCAL/tree/5f095cfb1757f2f17d367e4b054a458e6cabd4b8/xml/schema)

**Comment by isimluk** [comment]
I think here is the root cause of the issue:
 - https://github.com/usnistgov/OSCAL/commit/ca33e33c89171fb991d7838c39ac73f48e5add86
 - https://github.com/usnistgov/OSCAL/pull/608

**Comment by brianrufgsa** [comment]
@isimluk good catch! I'm investigating this with NIST now. It's possible they incorrectly converted the @id flag to NCName at the root, given it is their intention to always have a UUID in that field. 

Worst case, I'll update the handling to always prepend "uuid-". You can add that now to get past this validation error while we work the larger issue.

**Comment by brianrufgsa** [comment]
NIST is aware of this issue. They intend to address it by adding a UUID datatype, which fully resolve this issue. See usnistgov/metaschema#32 for more information and tracking.

They also recommend prepending "uuid-" for now. I will update the resolved profile catalogs to address this.

**Comment by isimluk** [comment]
Thanks! :clap:

**Comment by isimluk** [comment]
This is now resolved. 

All the xml files now validate with the latest OSCAL schemas. Thanks!

Verified by:
```
go get -u github.com/gocomply/oscalkit/cli/gocomply_oscalkit
for f in `find | grep '\.xml$'`; do gocomply_oscalkit validate $f; done
```
