### ISSUE TITLE
RAR submission for OSCAL

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#405]
# Action Item

**This is a ...**
  - [ X ] **investigation** - Something needs to be investigated further.

**This relates to ...**
  - [ X ] **General/Overall**
  - [ ] **Other**

## Describe the problem or enhancement

For JAB authorization, when applying for the  initial JAB P-ATO, the RAR must first be completed, and is valid for 1 year.  
The OSCAL models provided by FedRAMP do not include reference to which controls are required for RAR, and which are for SAP and SAR.  

Is there going to be a model for the RAR, so CSPs can submit the RAR through OSCAL and attain the P-ATO?  

## Goals:

Clear guidance on how to leverage the RAR workflow to achieve P-ATO.  

## Acceptance Criteria

- [ X ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- [ X ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by volpet2014** [comment]
None of existing FR OSCAL documentation addresses RAR use case.  RAR is somewhat similar to a SAR but we have no guidance / have never mapped a RAR to  SAR.  It is currently not supported at the moment but could be an interesting use case and perhaps something for the future if GSA would like to pursue.  Escalating to PMO review team SMEs for consideration.

**Comment by volpet2014** [comment]
Discussed with PMO and this will not be implemented into FedRAMP automation efforts as currently exists.  The Readiness Assessment Report is part of pre-assessment criteria prior to submission of OSCAL ducuments.  This will still remain the same for the forseeable future.
