### ISSUE TITLE
Artifact citation errors seem too strict

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#419]
* **This is a ...**
  - [ X] **concern** - I think something needs to be different.
  - [ ] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [ X] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ X] **Other**
CLI Validation rules when referencing an artifact.  
NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
CLI validation, the backmatter is a collection of artifacts that may not be referenced elsewhere in the document.  This could be a logo, image, historical ssp, etc....  While not a direct reference, could support the information within the SSP or is leveraged for other submissions.  Recommend reviewing the requirements for restrictions, since backmatter is not a separate model.  IE, attaching an annual SAP as history, results as an error, because it is not associated or leveraged within the SSP, but provides historical context.  

Provided the SSP validation and ssp where the errors were generated.  

This will be helpful for gui tools that are leveraging the backmatter to collect every artifact associated with the accreditation boundary even under different models, and will support a single model generation where references associate beyond their parent.  
[Validations.zip](https://github.com/GSA/fedramp-automation/files/11520240/Validations.zip)

* **What action would you like to see from the FedRAMP PMO?**

Would recommend having the artifact errors be informational in nature, but reduce the prevalence or structure so there is not as much noise in the production of a validation report.

**Comment by Telos-sa** [comment]
Additionally, found that some of the documents that are triggering an errors are not identified as required.  

Such as logo, master acronym list, and separation of duties.
![image](https://github.com/GSA/fedramp-automation/assets/127163717/2ad56dad-4fa0-483a-a83a-dc5a39729bea)

Would be really great if this was reviewed for Rev 5, to ensure there are updated templates and clear guidance on what should be attached and defined "type" for documents, so the information is clearly represented.

**Comment by Telos-sa** [comment]
@Telos-sa send the artifacts of our ZIP to FedRAMP with Dummy data.

**Comment by volpet2014** [comment]
As part of the early adopters workgroup, the rules associated with Schematron checks for back matter resources were relazed to warning level messages until the policy regarding rlink access as backmatter resources can be address fully.
