### ISSUE TITLE
fedramp-cli : Requires both IPv4 and IPv6.  

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#422]
# Describe the bug

Error in FedRAMP Validator requiring IPv6 if IPv4 prop is included.  

# Who is the bug affecting?
Anyone submitting an oscal ssp that defined inventory with ipv4 but not ipv6.  

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)
NO

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))
1.0.2

![image](https://github.com/GSA/fedramp-automation/assets/127163717/ab53136b-5fdc-4dee-8fb4-bbef861b601e)

# Expected behavior (i.e. solution)

Remove this error as it is not accurate.  There should be no requirement to have both.  Instead there should just be validating the structure if provided.  

And ensuring that the structure accounts for cidre, and shorthand. 

# Other Comments

Attached the validation report and the provided SSP
[Validations.zip](https://github.com/GSA/fedramp-automation/files/11520517/Validations.zip)

**Comment by Telos-sa** [comment]
@Telos-sa we will continue to ignore this error.

**Comment by volpet2014** [comment]
This has been address in the OEAW portal.   Pending updates to fedramp-automation GH repo on subsequent release.
