### ISSUE TITLE
JSON and YML baselines not updated during publishing

### ISSUE THREAD

**Issue by vmangat** [GSA/fedramp-automation#428]
# Describe the bug
Once the XML baselines are updated, they are successfully posted in the dist/content section. The resolved catalogs are updated automatically. The JSON and YML baselines are not updated automatically

# Who is the bug affecting?
We are held up in conversion of CSP SSPs to the correct version of Rev4 OSCAL SSP

# What version of OSCAL are you using? 1.0.4

# What is affected by this bug?
The JSON and YML Rev4 baselines

**Comment by volpet2014** [comment]
Confirmed this to be an issue with the GH workflow.   Looking into fixes ASAP.

**Comment by volpet2014** [comment]
Issue has been resolved.
