### ISSUE TITLE
Convert FedRAMP Laws and Regulations to OSCAL Back-Matter Syntax

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#43]
# Action Item

**This is a ...**
  - [ ] **enhancement** - Something could be better.

**This relates to ...**
  - [ ] **General/Overall**

## Describe the problem or enhancement

FedRAMP has an excel spreadsheet with applicable laws, regulations, standards, and guidance. This should be converted to OSCAL back-matter citation syntax to better enable tools to access it.

## Goals:

Convert the [FedRAMP Laws and Regulations file](https://www.fedramp.gov/assets/resources/templates/SSP-A12-FedRAMP-Laws-and-Regulations-Template.xlsx) to OSCAL.

## Dependencies:

None

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by ohsh6o** [comment]
Stiil TBD, need to follow up with NIST OSCAL development team on the current state of usnistgov/OSCAL#590 before planning and proceeding.

**Comment by volpet2014** [comment]
Collaborated with NIST on this and am removing the nist-collaboration tag and making this a PMO policy issue.  Need to discuss this with PMO as to why they are requiring folks to provide the fedramp laws, regulation etc. as part of an OSCAL package/back matter resource.

**Comment by volpet2014** [comment]
FedRAMP PMO has agreed to relax the requirement for this Laws and Regs backmatter resource during validations.
