### ISSUE TITLE
FedRAMP Baselines - Add Response Points

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#44]
# Action Item

**This is a ...**
  - [ ] **enhancement** - Something could be better.

**This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] **FedRAMP Baselines**

## Describe the problem or enhancement

Create a mechanism that indicates the FedRAMP-required response points for each control within the FedRAMP baselines, such that a tool reading the FedRAMP baseline (profile) is able to "know" which statement parts to present to SSP authors. 

For example, with 800-53 Revision 4, FedRAMP currently requires responses at the following statement parts:
- part a, part b.1, and part b.2 for all -1 controls (AC-1, AT-1, etc.)
- lettered parts (a, b, c, etc.) for all controls with lettered parts
- the control itself where there are no lettered parts exist.
(Note: 800-53r4 currently has numbered parts as subordinate to lettered parts within control definitions. In other words there are no controls that have numbered parts without also having lettered parts.)

While the response points can be observed by a human looking at the legacy MS Word template, or coded as rules into a tool, there is no clear machine-readable mechanism for FedRAMP to communicate or change the expected response points for each control. 

This enhancement would enable SSP tools to provide response fields at the correct level of granularity required by FedRAMP for each control, and allow FedRAMP to use different response points (when compared to the current pattern of requirements), for future 800-53 releases.

## Goals:

- Define a mechanism to clarify the required response point for an individual control as required by FedRAMP.
- Update FedRAMP baselines to reflect the appropriate response point for all FedRAMP-required controls.

## Dependencies:

None.
## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by brianrufgsa** [comment]
The intention is to define a FedRAMP extension to be used within profiles to annotate the FedRAMP-required response points for a control, then update the FedRAMP profiles to reflect the required response points for each control.

**Comment by ohsh6o** [comment]
Will need to review current extension work and the current state of this issue.

**Comment by ohsh6o** [comment]
Reviewing current baselines, resolved catalog profiles, and documentation, it appears this was implemented by Brian prior to his departure. Will review for quality checks for 1.0.0 final release as needed.
