### ISSUE TITLE
Response Points missing from Rev-5 Baseline Catalogs

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#443]
# Describe the bug

The Rev 5 baseline catalogs are missing the response points for statements and objectives.  This is resulting in duplicate coverage of statements (in some cases triplicate) and will require a heavy lift for any customer to capture their control implementation responses across multiple locations.  
An exert from the High Rev 5 SSP Appendix A, showing the duplicative coverage across a single control

![image](https://github.com/GSA/fedramp-automation/assets/127163717/34cf717f-9d70-47a7-82a9-b7dd8774e791)

This contradicts the setup of the Rev 4 Baseline profile catalog, where each required statement had a response point, indicating it must be answered for.  

# Who is the bug affecting?

Any user that wants to transition to Rev 5 or is planning to use rev 5 document templates, and OSCAL.  

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)
See Rev 5 SSP Appendix A for an example, where each statement within each control is in SCOPE. 

If so, please do not open an issue here. Follow the guidance in [this repository's README](https://github.com/GSA/fedramp-automation#support-and-oscal-deprecation-strategy) and contact [info@fedramp..gov](mailto:info@fedramp.gov).

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

# What is affected by this bug?

All Rev 5 Baseline Catalog Profiles

# When does this occur?

With the release of the Rev 5 baseline catalog profiles.  If we look at the example for AC-1.  This is the issue for the implementation statement (Based on Document).  Where duplicate statements will be captured at the higher level response points.  

Part a: compiled the answers from parts a1, a1a, a1b, and a2. 
Part a1: compiled the answers from parts a1a, and a1b
Part a1a: (lowest granularity) - this should be a response point
Part a1b: (lowest Granularity) - This should be a response point
Part b: (lowest granularity) - this should be a response point
part c: compiled the answers from parts c1 and c2
part c1: (lowest granularity) - this should be a response point
part c2: (lowest granularity) - this should be a response point.  

# How do we replicate the issue?

Open either the Baseline catalog profile, or the SSP Appendix A and compare to the SSP for rev 4, or the Baseline catalog of Rev 4.  (Or the SRTMs).  Search for "response-point" and note that they do not exist in Rev 5, only in rev 4.  Note how rev for provides scope, that is not present in rev 5.  

# Expected behavior (i.e. solution)

Response points should be added so the SSP documentation and OSCAL template can be compiled only with what is required, and prevent duplicate and extra work.  

IE for AC1, the response points could be (AC-1.a, AC-1.b, AC-1.c) or for more specific granular statements (AC-1.a.1, AC-1.a.2, AC-1.a.2, AC-1.b, AC-1.c.1, AC-1.c.2). 

# Other Comments

Makes it difficult to build a template for customers to use when the data is going to change.  Need defined statements to answer.

**Comment by volpet2014** [comment]
We are aware that these are missing from the current Rev 5 profiles and resolved-profile-catalogs.  This was intentional due to an in process project with the PMO to designate both "core" controls and "tailor" the response points for Rev 5.  This will be addressed soon in a future release of the OSCAL baselines (profiles).    We are working toward resolving this as soon as possible.

**Comment by Rene2mt** [comment]
See the proposed resolution in this PR: https://github.com/GSA/fedramp-automation/pull/502
