### ISSUE TITLE
SAP validator not reading metadata of responsible parties against party entries

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#447]
# Describe the bug

When validating a FedRAMP OSCAL SAP, the party UUID metadata in responsible-parties falsely reports that there is no matching party with the same UUID. 

# What version of OSCAL are you using? 

OSCAL version 1.0.0

# How do we replicate the issue?

1. Run the attached SAP through the validator
[FedRAMP Example Project_OSCAL_SAP.json.zip](https://github.com/18F/fedramp-automation/files/12070691/FedRAMP.Example.Project_OSCAL_SAP.json.zip)

3. The following errors appear in 4.11, 4.12, and 4.21 despite the SAP having matching UUIDs for all parties and their respective responsible-parties section in metadata.
![image](https://github.com/18F/fedramp-automation/assets/127163717/397b21ac-c767-44e2-b4c0-dcfacd4c72b9)

# Expected behavior (i.e. solution)

These errors should not appear when there are matching UUIDs between the metadata for all parties and responsible-parties.

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
