### ISSUE TITLE
SAP validation error for controls in the associated SSP

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#449]
# Describe the bug

When validating a FedRAMP OSCAL SAP, an error appears for included controls not being in the associated SSP when only the SAP has been uploaded. 

# What version of OSCAL are you using? 

OSCAL version 1.0.0

# How do we replicate the issue?

1. Run the following SAP through the validator:
[FedRAMP Example Project_OSCAL_SAP.json.zip](https://github.com/18F/fedramp-automation/files/12070691/FedRAMP.Example.Project_OSCAL_SAP.json.zip)

2. The following error appears in 4.1:
<img width="595" alt="Screenshot 2023-07-18 at 16 43 12" src="https://github.com/18F/fedramp-automation/assets/127163717/c8dbb356-d1d4-43c2-b2eb-b5e516f927d2">

# Expected behavior (i.e. solution)

Assertions involving the associated SSP should not be marked as errors when only the SAP is uploaded. Passing this test would require a full package with artifacts to be able to perform a cross reference.

**Comment by volpet2014** [comment]
Automation Team agrees and has relaxed this to a warning in OEAW portal validations.   Updates to fedramp-automation GH pending for this relaxation.
