### ISSUE TITLE
Implement Basic CI/CD Automation Within Repository

### ISSUE THREAD

**Issue by brianrufgsa** [GSA/fedramp-automation#45]
# Action Item

**This is a ...**
  - [ ] **enhancement** - Something could be better.

**This relates to ...**
  - [ ] **General/Overall**
  - [ ] **Other**

## Describe the problem or enhancement

Establish basic CI/CD functionality within the fedramp-automation repository.

## Goals:

- validate OSCAL content relative to the NIST OSCAL syntax
- convert provided formats to alternate formats (XML -> JSON, or JSON -> XML)
- validate if non-OSCAL XML, JSON, and transforms are well-formed

## Dependencies:

None.
This relates to usnistgov/OSCAL#639.

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I believe this work is done.
