### ISSUE TITLE
SAP validation error for locations in the associated SSP

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#450]
# Describe the bug

When validating a FedRAMP OSCAL SAP, an error appears for a location not being in the associated SSP when only the SAP has been uploaded. 

# What version of OSCAL are you using? 

OSCAL version 1.0.0

# How do we replicate the issue?

1. Run the following SAP through the validator:
[FedRAMP Example Project_OSCAL_SAP.json.zip](https://github.com/18F/fedramp-automation/files/12070691/FedRAMP.Example.Project_OSCAL_SAP.json.zip)

2. The following error appears in 4.3.1:
<img width="593" alt="Screenshot 2023-07-18 at 16 47 32" src="https://github.com/18F/fedramp-automation/assets/127163717/6cbfb44b-901d-4835-979a-b05c31fe581d">

# Expected behavior (i.e. solution)

Assertions involving the associated SSP should not be marked as errors when only the SAP is uploaded. Passing this test would require a full package with artifacts to be able to perform a cross reference.

**Comment by volpet2014** [comment]
This was addressed by relaxing validations to warnings in the Early Adopter's working group until Phase 3 of the OEAW process where we will be accepting full packages.
