### ISSUE TITLE
Invalid Links to SAR Guide

### ISSUE THREAD

**Issue by brian-easyd** [GSA/fedramp-automation#466]
# Describe the bug

When viewing the page: 
[https://github.com/GSA/fedramp-automation/tree/master/documents](https://github.com/GSA/fedramp-automation/tree/master/documents)

Links to the _Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)_ do not work. Note these links are in:
[https://github.com/GSA/fedramp-automation/blob/master/documents/README.md](https://github.com/GSA/fedramp-automation/blob/master/documents/README.md)

# Who is the bug affecting?

Anyone trying to find the SAR guide via the links.

# Is this report specifically related to [the Word or Excel files from fedramp.gov?](fedramp.gov/documents-templates/)

No

# What version of OSCAL are you using? (Check our info on [supported OSCAL versions](https://github.com/GSA/fedramp-automation/blob/master/README.md#support-and-oscal-deprecation-strategy))

N/A

# What is affected by this bug?

Impedes a user's ability to find the document.

# When does this occur?

When browsing the GitHub repo via a web browser.

# How do we replicate the issue?

{What are the steps to reproduce the behavior?}

1. Visit either: 
  - [https://github.com/GSA/fedramp-automation/blob/master/documents/README.md](https://github.com/GSA/fedramp-automation/blob/master/documents/README.md); OR
  - [https://github.com/GSA/fedramp-automation/blob/master/documents](https://github.com/GSA/fedramp-automation/blob/master/documents/README.md)
2. Click on either the Rev 4 or Rev 5 links next to _Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)_
3. Observe _404 Page Not Found_ error.

![Screenshot 2023-08-15 105619](https://github.com/GSA/fedramp-automation/assets/106116211/994385f7-5210-4fb8-b18c-502567c2f12f)

# Expected behavior (i.e. solution)

Opens PDF file.

# Other Comments

None

**Comment by volpet2014** [comment]
Added @Rene2mt to issue for him to address in next revision release.

**Comment by volpet2014** [comment]
Fixed errand file name link for SAR
