### ISSUE TITLE
Validator requires invalid "MIXED" method in observation.

### ISSUE THREAD

**Issue by ConnorHiteSA** [GSA/fedramp-automation#468]
**Extended Description**
There is an error in the FedRAMP validator (for SAR) that differs from NIST’s allowed values. The check depicted below requires an observation type of ‘Historic’ to also have a method value of ‘MIXED’:
![image](https://github.com/GSA/fedramp-automation/assets/109171182/1f5d498b-471f-49a9-8ef0-00ba6236be8c)

‘MIXED’ is not a valid value per NIST. Their list of allowed values include:
![image](https://github.com/GSA/fedramp-automation/assets/109171182/e8a5972c-f9f7-47f5-a9d7-abb79a9d8b98)

Recommendation: Instead of writing ‘MIXED’, you could require the list to contain each of the applicable values (Interview, examine, test). This is how NIST recommends implementation: 
![image](https://github.com/GSA/fedramp-automation/assets/109171182/4fb58bfa-ddd9-4cbb-a8ef-85f771929bdf)

This is how ours currently outputs:
![image](https://github.com/GSA/fedramp-automation/assets/109171182/3def8a33-7b6d-4fda-a6d0-bafb42ebd23e)

**Preconditions**
- Preconditions…

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- More acceptance criteria…

**Story Tasks**
- [ ] Tasks…

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [X] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [X] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by dimitri-zhurkin-vitg** [comment]
Connor,

Could you share your code for these two observations:
1. 0b277aa2-771e-5131-9afc-228af23bb5df
2. 7c21c0ca-e06b-5158-beac-0fa382d96e09

From the screen shots, it sounds like you might have a collision of types and methods:
```
<observation uuid="0b277aa2-771e-5131-9afc-228af23bb5df">
    <method>INTERVIEW</method>
    <type>historic</type>
</observation>
```
and
```
<observation uuid="7c21c0ca-e06b-5158-beac-0fa382d96e09">
    <method>EXAMINE</method>
    <type>historic</type>
</observation>
```

**Comment by aj-stein-gsa** [comment]
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
