### ISSUE TITLE
Generating RAR workflow (AS modified SAP, SAR, and POAM).  

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#477]
# Action Item

**This is a ...**
  - [ ] **fix** - Something needs to be different.
  - [ ] **enhancement** - Something could be better.
  - [ X ] **investigation** - Something needs to be investigated further.

**This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ X ] **Other**

NOTE: For issues related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

## Describe the problem or enhancement

The RAR requests information that is not in the SSP, and is not defined as part of the OSCAL model.  

## Goals:

Recommendation:  Identify which objectives are included in the RAR.  Add the dependancies from the RAR into the SSP (API should be a component definition).  And create a modified SAP, SAR, and POAM report that is based on the RAR (like with an annual assessment).  

This way the "Ready" Status incorporates OSCAL, and the requirements can be assessed programmatically.  

## Dependencies:

Modify the OSCAL SSP:  Incorporate API as a component.  
Modify OSCAL SAP: Add Ready as part of an assessment objective, and scope (currently is full, and annual assessment.  NOTE:  to support conmon in the future, additional objectives like "Feature Addition" and "Security Relevant Change" should also be incorporated in the SAP, for scoping.  

No change identified for SAR and POAM models.  

## Acceptance Criteria

- [ X ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- [ X ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by volpet2014** [comment]
See closed ticket RAR submission for OSCAL #405
