### ISSUE TITLE
Validator requires invalid "other-than-satisfied" state in finding.

### ISSUE THREAD

**Issue by TonyCiceroUS** [GSA/fedramp-automation#481]
**Extended Description**
The FedRAMP validator (SAR) has allowed values that differ from NIST's allowed values. According to rule below, the allowed FedRAMP state values for a target of objective-id type are 'satisfied' or 'other-than-satisfied'. 

![image](https://github.com/GSA/fedramp-automation/assets/143224415/1b7b6d08-151e-4fe1-929d-bde458f47469)
https://github.com/gsa/fedramp-automation/blob/9d82427b6cd2dbaee5c24ad2ef4f995600c66454/src/validations/rules/rev4/sar.sch#L515-L526

However, 'other-than-satisfied' is not an allowed value per NIST.

![image](https://github.com/GSA/fedramp-automation/assets/143224415/0b99d8ff-da4f-4fe3-91b9-403841bae9ff)

**Preconditions**
- Preconditions…

**Acceptance Criteria**
- [ ] All Schematron assertion messages are declarative statements which affirm the positive test outcome.
- [ ] All Schematron assertion diagnostic messages are declarative statements which explain the negative test outcome.
- [ ] The Schematron code has no assertion failures when validated using `src/validations/styleguides/sch.sch` using the `basic` phase.
- [ ] XSpec unit tests for positive and negative Schematron assertion outcomes accompany all Schematron assertions (where feasible).
- More acceptance criteria…

**Story Tasks**
- [ ] Tasks…

**Definition of Done**
 - [ ] Acceptance criteria met
 - [ ] Unit test coverage of our code > 95%
 - [ ] Automated code quality checks passed
 - [ ] Security reviewed and reported
 - [ ] Reviewed against plain language guidelines
 - [ ] Code must be self-documenting
 - [ ] No local tech debt
 - [ ] Load/performance tests passed – needs to be created/automated
 - [ ] Documentation updated
 - [ ] Architectural Decision Record completed as necessary for significant design choices
 - [ ] PR reviewed & approved
 - [ ] Source code merged

**Comment by dimitri-zhurkin-vitg** [comment]
Fixed in rev 5.
