### ISSUE TITLE
Requesting an “Access to Service and Connection” permission

### ISSUE THREAD

**Issue by ConnorHiteSA** [GSA/fedramp-automation#515]
# Action Item

**This is a ...**
  - [ ] **fix** - Something needs to be different.
  - [X] **enhancement** - Something could be better.
  - [ ] **investigation** - Something needs to be investigated further.

**This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [X] **General/Overall**
  - [ ] **Other**

NOTE: For issues related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

## Describe the problem or enhancement

The Rev 5 changes to Interconnections and Services requires a new permission to be created. We are requesting the addition of an “Access to Service and Connection” permission to coincide with the Authorized Users field attributed to each interconnection.

## Goals:

We would like this permission to be created, in order to enable an accurate creation of the Authorized Users entry.

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [X] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

## Other Comments

{Add any other context about the problem here.}

**Comment by volpet2014** [comment]
Telos to add prop to their output and FedRAMP will need need to update SSP guide to bring it in line with property.
