### ISSUE TITLE
CA-8 (2) Typo in the Additional Guidance Part

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#551]
### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [X] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP OSCAL Validations**

### What happened?

The text for the additional guidance part of CA-8(2) mentions  **CM-2** instead of **CM-8(2)**.

![CA-8 2_typo](https://github.com/GSA/fedramp-automation/assets/76444659/5e2c201c-35d7-4b2b-9dc8-3ec034b598d9)

### How do we replicate this issue?

The issue was discovered in the MS Word SSP template, but originates from source OSCAL profiles.

See high profile - https://github.com/GSA/fedramp-automation/blob/8847162bbca6b0bb2a60806d04ae966e3da2f93c/src/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline_profile.xml#L2712

And moderate profile - https://github.com/GSA/fedramp-automation/blob/8847162bbca6b0bb2a60806d04ae966e3da2f93c/src/content/rev5/baselines/xml/FedRAMP_rev5_MODERATE-baseline_profile.xml#L2369

### Where, exactly?

The `title` in `<part id="ca-8.2_fr" name="item">`  should say **CA-8(2)** where it says **CM-2**

**Comment by david-waltermire** [comment]
Fixed by #552.
