### ISSUE TITLE
Create and Publish Validation Rules

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#56]
# Action Item

**This is a ...**
  - [ ] **enhancement** - Something could be better.

**This relates to ...**
  - [ ] **General/Overall**

## Describe the problem or enhancement

The rules and checklists to perform manual adjudication of FedRAMP authorization packages are well defined. Many of them can be fully automated, especially the initial checks for completeness. 

Where the review rules and checklists can be automated, there are many approaches. Ideally, our approach should allow these rules to be published and re-used by tool developers. This offers several high-level advantages:

1. Reduce the level of effort for tool developers
1. Ensure consistency of content validation across tools.
1. Easily publish updates to our validation checks that can be instantly incorporated into existing tools.
1. Provides the ability for stakeholders to validate their content before submission to the PMO
 

## Goals:

- Identify and prioritize validation rules
- identify a technology/standard for creating and publishing validation rules
- produce guidance on adopting validation rules

## Dependencies:

None. 

## Acceptance Criteria

- [x] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

- [x] Validation rules identified
- [x] Technology/standard selected
- [x] documentation provided

## Other Comments

OSCAL is designed with schematron validation in mind. Schematron is a 4th generation language (4GL), which can be used by most modern programming languages. 

It was designed to provide a common syntax for defining business rules/validation activities on XML content, separate from the presentation logic and UI logic.

**Comment by brianrufgsa** [comment]
This issue should replace issue usnistgov/OSCAL#272

**Comment by ohsh6o** [comment]
Will coordinate with 10x ASAP team [per their development and roadmap in the Github project board](https://github.com/orgs/18F/projects/22).

**Comment by ohsh6o** [comment]
Per discussion with the FedRAMP PMO, this work will be scheduled for a subsequent release after the FedRAMP OSCAL 1.0.0 release. Removing this from that milestone and will plan this as part of the subsequent FedRAMP OSCAL 1.1.0 release.

/cc @zachbaldwin
