### ISSUE TITLE
[Feedback]: Revision History elements in Metadata (Metaschemas) 

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#568]
### This is a ...

question - need to understand something

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [X] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [X] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [X] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [X] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP OSCAL Validations**

### What is your feedback?

<img width="551" alt="Screenshot 2024-03-14 at 10 34 40 AM" src="https://github.com/GSA/fedramp-automation/assets/127163717/00048070-0a88-459d-b267-f85ca810027f">

In creating the revisions history for the SSP schema, would it be appropriate to include revisions for all of the Appendices, or only include revision history for the SSP itself?

Because FedRAMP requires these appendices as part of the SSP, we thought it would be appropriate to include revisions for all of them in the schema.

### Where, exactly?

OSCAL Metaschemas v1.1.2: https://pages.nist.gov/OSCAL-Reference/models/v1.1.2/system-security-plan/json-outline/

**Comment by aj-stein-gsa** [comment]
Hi @Telos-sa, this question is good, but is really about OSCAL generally, which in this case FedRAMP follows without customization for our requirements. The revisions section is for the revision history of the document itself (the SSP, the POAM, the SAP, or the SAR). The source code for the models and website say this, albeit maybe not as clearly as we'd like.

https://github.com/usnistgov/OSCAL/blob/v1.1.2/src/metaschema/oscal_metadata_metaschema.xml#L29-L31

I am going to close this issue for now. Feel free to reopen if you need further clarification.
