### ISSUE TITLE
Update and Standardize  src/content/rev5/resources/xml/FedRAMP_extensions.xml in metaschema format

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#587]
### This is a ...

improvement - something could be better

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)

### User Story

Requesting that this document, or something like this, be created for each model that outlines the FedRAMP requirements, in a way that they can be standardized and ingested.  For instance, where props are created, sometimes the FedRAMP created prop identifies the name spaces and sometimes it does not.  

### Goals

Would like to standardize this process so that the programmatic requirements can be layered onto the NIST SSP metaschema requirements to create a full SSP template to generate, will all required/expected props, their values, and any additional validation assumptions (like core controls, required response points, parameters, etc) if referenced in baseline profile. 

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by aj-stein-gsa** [comment]
A lot has changed since May, so I may contradict Rene a little here as it pertains to this issue. Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.
