### ISSUE TITLE
FedRAMP/DoD Reciprocity in OSCAL: Investigate 

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#59]
# Action Item

**This is a ...**
  - [ ] **enhancement** - Something could be better.

**This relates to ...**
  - [ ] **General/Overall**

## Describe the problem or enhancement

A reciprocity exists between FedRAMP and DoD where a CSP can achieve a FedRAMP authorization, then DoD adjudicated the package by focusing only on the additional IL4 or IL5 requirements. 

DISA indicates it would be helpful to have guidance regarding the additional content that should appear in an OSCAL-based FedRAMP package when it is intended for further adjudication by DoD after a FedRAMP authorization.

This may be a larger effort; however, we should start by investigating and quantifying the additional information requirements. 

## Goals:

- Identify the information requirements for DOD reciprocity in a FedRAMP OSCAL authorization package

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] Level of effort defined and attached to this issue

**Comment by ohsh6o** [comment]
Will need to discuss further and investigate with the FedRAMP PMO.

**Comment by ohsh6o** [comment]
Closing for now, as now formal feedback from DISA colleagues. Will re-open or open a new issue when official release of CCI mapping and realizing reciprocity through OSCAL mechanics is ready for cross-agency collaboration.
