### ISSUE TITLE
Implement Dependabot in FedRAMP-Automation Repository

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#605]
### This is a ...

improvement - something could be better

### This relates to ...

- [x] Other

### User Story

NOTE: This issue is for a backlog item, it does not have an explicit user story. The goal is for the development team, not necessarily external stakeholders.

### Goals

Establish ongoing automated updates to packages.  Also, remove Snyk where no longer needed (e.g., legacy website )

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by aj-stein-gsa** [comment]
@david-waltermire you still work on this? If not, I will presume it is time for me to pick this up.

**Comment by aj-stein-gsa** [comment]
We should try to take care of this sometime tomorrow or worst case Friday because we will remove a bunch of old dependencies from the repo that have security notices for maintainers. Once we wipe the slate clean we can have this track new code deps and stay better on top of it.

**Comment by aj-stein-gsa** [comment]
Also work this very soon alongside #692.
