### ISSUE TITLE
Help with ERROR CODE:SXJS0006 "Not Found: http://localhost:5173/rules/oscal_ssp_json-to-xml-converter.sef.json"

### ISSUE THREAD

**Issue by GurkhaShieldForce** [GSA/fedramp-automation#625]
### This is a ...

research - something needs to be investigated

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)

### User Story

I'm tying to process OSCAL file to inspect validations rules and apply them.

### Goals

I'm tying to process OSCAL file to inspect validations rules and apply them. I have the ASAP dev server running on http://localhost:5173.
 
After I upload my "FedRAMP-SSP-OSCAL-Template.json" I keep getting a 
"Failed to read JSON input http://localhost:5173/rules/oscal_ssp_json-to-xml-converter.sef.json: XError:Failed to read http://localhost:5173/rules/oscal_ssp_json-to-xml-converter.sef.json(Not Found: http://localhost:5173/rules/oscal_ssp_json-to-xml-converter.sef.json); code:SXJS0006"

Can someone please point me to the right direction? 

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.

**Comment by aj-stein-gsa** [comment]
Thanks for updating this issue, @Rene2mt. At this time we are not moving forward with the maintenance of this web-based test application with the legacy constraints. Unfortunately, we will close this issue for now. Please feel free to reach out and discuss further if you have any questions, comments, or concerns regarding that with the contact info here.

https://automate.fedramp.gov/contact/
