### ISSUE TITLE
Fedramp Constraints release strategy

### ISSUE THREAD

**Issue by wandmagic** [GSA/fedramp-automation#626]
### This is a ...

improvement - something could be better

### This relates to ...

- [x] the **FedRAMP OSCAL Constraints**

### User Story

As a maintainer of a digital authorization package or developer of a GRC tool, I want a strategy that explain what constraints 

### Goals

- [ ] Develop and publish a strategy to release constraints:
  - [ ] incrementally; 
  - [ ] with a rationale for categorizing and prioritizing constraints; and
  - [ ] a high-level roadmap (without dates, milestones only) and how that categorization will inform the sequence of development tasks

### Acceptance Criteria

- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story, specifically a document that provides a high-level overview of the following (per https://github.com/GSA/fedramp-automation/issues/626#issuecomment-2419788279):
  - [ ]  Key principles (correctness and completeness before analytical; simple before complex; SSP first; others I have not included you think important)
  - [ ]  The list of "features" we use to label a requirement for prioritization (no/partial/completely automatable with constraint mechanism; does or does/not requires hybrid automation with OSCAL with platform workflow; is it a checklist item; et cetera). This is not exhaustive.
  - [ ]  A commitment to logically grouping constraints (not a list of pre-built groups themselves) grouped into release candidates.

### Other information

1. Update goals and ACs from comment here for clarity.

**Comment by aj-stein-gsa** [comment]
@Rene2mt I would love to catch up with you and work together on this, given your bandwidth, or pick this work up.

**Comment by aj-stein-gsa** [comment]
Given recent chatter and some public technical comms that will go out soon, it is time for Rene, I, and the larger team to discuss this further and work it out. I am moving this one to in-progress, more to follow!

**Comment by aj-stein-gsa** [comment]
@brian-ruf had some thoughts and wanted to give feedback and/or get more involved on this work per a discussion in standup. I will ping you and catch up, probably with @Rene2mt, later today, availability permitting.

**Comment by brian-ruf** [comment]
Working on a draft document here:
[https://docs.google.com/document/d/1KrlSSrsD-JsFTevMfdA2IKgnlF_KYkpkoVdwGffwpOc/edit?usp=sharing](https://docs.google.com/document/d/1KrlSSrsD-JsFTevMfdA2IKgnlF_KYkpkoVdwGffwpOc/edit?usp=sharing)

**Comment by brian-ruf** [comment]
@aj-stein-gsa the draft is in our team shared drive. So everyone on the team should have access to the link I posted above.

**Comment by aj-stein-gsa** [comment]
I am going to unassign myself for a bit and let @brian-ruf and/or @Rene2mt work on a short strategy document in Google Drive that focuses on this work.

1. Key principles (correctness and completeness before analytical; simple before complex; SSP first; others I have not included you think important)
1. The list of "features" we use to label a requirement for prioritization (no/partial/completely automatable with constraint mechanism; does or does/not requires hybrid automation with OSCAL with platform workflow; is it a checklist item; et cetera). This is not exhaustive.
1. A commitment to logically grouping constraints (not a list of pre-built groups themselves) grouped into release candidates.

If you all can drop the link in an update comment and ping me when ready, that would be very helpful, please and thank you.

**Comment by wandmagic** [comment]
what will our first "fedramp-version" string be?

**Comment by aj-stein-gsa** [comment]
> what will our first "fedramp-version" string be?

Wrong issue? I don't understand how this comment relates to the scope of work in #626. Can you elaborate?

**Comment by wandmagic** [comment]
I understood that constraints will be released with version numbers, just wondering if we already have one and it will be 2.0.0
or we will start with 0.0.1 etc...  and when we bring out develop branch to master will that be considered 1.0.0 we tag and that is our first official release?

**Comment by brian-ruf** [comment]
Initiated issue/Epic #804 for the SSP Completeness checks. Within, that issue is a task list with linked stories that break down the work.

**Comment by aj-stein-gsa** [comment]
> I am going to unassign myself for a bit and let @brian-ruf and/or @Rene2mt work on a short strategy document in Google Drive that focuses on this work.
>  ...

@brian-ruf and @Rene2mt I want to circle back on the substance of https://github.com/GSA/fedramp-automation/issues/626#issuecomment-2419788279 and bring this comment back into focus.

We have a long-form document that includes a strategy, plan, and tactical information. Instead of a short Google doc, I think we are at the point where we need to have a high level explanation of the 3 topics in a strategy from that comment and we need to document them in GitHub. We discussed completing this document to complete during or shortly after Thursday's Data Bytes meeting, and it is time to move forward.

As the presentation looks very solid, can we begin work on the PR? I guess an ADR is a good fit for this. I have adjust the goal and acceptance criteria accordingly to be more explicit than the com

**Comment by wandmagic** [comment]
I concur we need an ADR do document our decision regarding our release strategy

**Comment by brian-ruf** [comment]
@Rene2mt and @brian-ruf agreed that next steps are:
- Draft ADR summarizing decision (and especially the goals in [AJ's comment above](https://github.com/GSA/fedramp-automation/issues/626#issuecomment-2419788279))
- Seek review and approval on ADR
- Seek review and approval on drafted [Constraint Management Wiki Page](https://github.com/GSA/fedramp-automation/wiki/Constraint-Management)

**Comment by brian-ruf** [comment]
ADR-12 is drafted and pending two more reviews in PR #830. 
The Wiki page is also drafted and needs a review. 
Comments on that review should be added to this issue.
