### ISSUE TITLE
create a configuration file eg .oscal-config which determines the current oscal-cli version

### ISSUE THREAD

**Issue by wandmagic** [GSA/fedramp-automation#628]
### This is a ...

fix - something needs to be different

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)

### User Story

as a fedramp-automations developer, i need to know what version of oscal-cli to have installed rather than using latest

### Goals

maintain oscal version as a configuration file

### Dependencies

oscal-js repo will support this feature

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by aj-stein-gsa** [comment]
I will assign this work to @wandmagic and cite the related #692 and #903 PR, as it so happens this tooling update will take care of this issue as well, per updates discussed today. I forgot this specific request was written up separatelt in the backlog.
