### ISSUE TITLE
Local Validation Setup Instructions

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#629]
### This is a ...

improvement - something could be better

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)

### User Story

As a FedRAMP OSCAL content author, I need clear instructions on how to setup my local environment with FedRAMP provided validation tools (e.g., OSCAL-CLI, OSCAL-JS, etc.), so that I can ensure the OSCAL content I generate meets FedRAMP's requirements.

### Goals

- [ ] Documentation should be provided as Markdown files in the FedRAMP automation GitHub repository (and possibly referenced from [FedRAMP Developer Hub site](https://automate.fedramp.gov)).
- [ ] Documentation should provide example of how to do a standard validation (e.g., validation using core NIST Metaschema constraints)
- [ ] Documentation should provide example of how to do FedRAMP specific validations (e.g., validation using external Metaschema constraint definitions)
- [ ] Documentation should cover generating SARIF outputs and use in IDE
- [ ] Documentation _may_ provide examples of other useful capabilities (e.g., profile resolution)

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by Rene2mt** [comment]
- PR GH-636

**Comment by aj-stein-gsa** [comment]
Woops, close out in favor of #642.
