### ISSUE TITLE
FEDRAMP-POAM-OSCAL-Template.json does not validate against oscal_poam_schema.json

### ISSUE THREAD

**Issue by jasswalkjr** [GSA/fedramp-automation#63]
# Describe the bug
FEDRAMP-POAM-OSCAL-Template.json does not validate against oscal_poam_schema.json.

# Who is the bug affecting?
All users of the FEDRAMP-POAM-OSCAL-Template.json file.

# What is affected by this bug?
FEDRAMP-POAM-OSCAL-Template.json

# When does this occur?
Occurs when you attempt to validate the file against the schema.

# How do we replicate the issue?
Validate FEDRAMP-POAM-OSCAL-Template.json against oscal_poam_schema.json

# Expected behavior (i.e. solution)
FedRAMP-POAM-OSCAL-Template.json should validate against oscal_poam_schema.json

# Other Comments
None

**Comment by david-waltermire-nist** [comment]
The current [POAM template](https://github.com/GSA/fedramp-automation/tree/master/templates/poam/json) should now validate against the latest OSCAL JSON schema.
