### ISSUE TITLE
Update main repo README with link to validation instructions

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#640]
### This is a ...

improvement - something could be better

### This relates to (documentation for all the below more or less):

- [x] the **FedRAMP OSCAL Registry**
- [x] the **FedRAMP OSCAL baselines**
- [x] the **Guide to OSCAL-based FedRAMP Content**
- [x] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [x] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [x] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [x] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [x] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [x] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [x] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [x] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)

### User Story

As a FedRAMP practitioner, I need to easily find instructions for how to get started with local validations, so that I can ensure my OSCAL content (e.g., SSP) meets FedRAMP requirements.

### Goals

Update the main [README](https://github.com/GSA/fedramp-automation/blob/master/README.md):

- [x] **Dependencies** section references OSCAL 1.0.4 but should be updated to 1.1.2
- [x] Fifth sub-bullet in the **Dependencies** section mentions NIST SP 80-53 Revision 4 in OSCAL.  Update to Revision 5.
- [x] Fifth sub-bullet in the **Dependencies** section link to NIST OSCAL Revision 5 baselines is broken.
- [x] **Rules Documentation** section should either be removed or some verbiage added to note that this work is deprecated.
- [x] **Developer Notes** review and update as needed
- [x] **Implementation details** should be removed
- [x] Add a section about validating OSCAL content.  This section should:
  - Reference https://automate.fedramp.gov/documentation/general-concepts/oscal-layers-of-validation/
  - Provide brief description and link to https://github.com/GSA/fedramp-automation/tree/feature/external-constraints/src/validations/constraints

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by aj-stein-gsa** [comment]
I talked to @kyhu65867 and she is nominally open to start working on this next week. If not, she will ping me/us Monday or early next week and regroup accordingly.

**Comment by aj-stein-gsa** [comment]
@kyhu65867 it seems like you have been working this one for a while in #771 so I am going to move this issue to in progress.

**Comment by aj-stein-gsa** [comment]
Actually I take that back, I will move it into review as we have been incrementally tweaking away at it for a bit now.

**Comment by aj-stein-gsa** [comment]
Snap this one is done.
