### ISSUE TITLE
Add Cardinality to Official FedRAMP Values (XML)

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#65]
* **This is a ...**
  - [ ] **concern** - I think something needs to be different.
  - [ ] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [X] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [X] the **FedRAMP OSCAL Registry** (Excel File)
  - [X] the **FedRAMP OSCAL Registry** (XML)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [X] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

[FedRAMP XML values file](https://github.com/GSA/fedramp-automation/blob/master/resources/xml/fedramp_values.xml)

One potential location, as expressed as an XPath query, would be here.

`//f:value-set/cardinality`

* **What is your feedback?**

Per conversation with @brianrufgsa, in order to ease development of validation tooling with Schematron, or any other XML-based tools that will look at the [FedRAMP XML values directly](https://github.com/GSA/fedramp-automation/blob/master/resources/xml/fedramp_values.xml), it might be prudent to evaluate bringing in the cardinalities expressed in the FedRAMP OSCAL Registry Excel files as `<cardinality/>` element for applicable `<value-set/>` items where the cannonical OSCAL implementation does not specify them (and a user relies on defaults) or FedRAMP wishes to override the explicitly set NIST OSCAL default.

The layout can be something simple, potentially like this.

```xml
   <value-set name="control-implementation-status">
      <cardinality min="1" max="1">
      <formal-name>Control Implementation Status</formal-name>
      <description>The implementation status of the control.</description>
      <binding pattern="implemented-requirement/annotation[@name='implementation-status']/@value"/>
      <allowed-values allow-other="no">
         <enum value="implemented" short-label="Implemented">Implemented</enum>
         <enum value="partial" short-label="Partial">Partially Implemented</enum>
         <enum value="planned" short-label="Planned">Planned</enum>
         <enum value="alternative" short-label="Alternative">Alternative Implementation</enum>
         <enum value="not-applicable" short-label="N/A">Not Applicable</enum>
      </allowed-values>
   </value-set>
```

In some cases, as discussed, we would want a `max` attribute that is `unbounded` and not an integer value, to align with the registry in Excel and existing Metaschema definitions/style as exposed in XSD. I just picked attachment-type as an example, without much intention.

```xml
   <value-set name="attachment-type">
      <cardinality min="0" max="unbounded">
      <formal-name>Attachment Type</formal-name>
      <description>Identifies the type of attachment.</description>
      <binding pattern="resource/prop[@name='type'][@ns='https://fedramp.gov/ns/oscal']"/>
      <allowed-values allow-other="yes">
         <enum value="law" short-label="Law">Law or Statute</enum>
         <enum value="regulation" short-label="Regulation">Regulation or Directive</enum>
         <enum value="standard" short-label="Standard">Industry Standard</enum>
         <enum value="guidance" short-label="Guidance">Guidance</enum>
         <enum value="pii" short-label="P.I.I.">Privacy Impact Information</enum>
         <enum value="policy" short-label="Policy">Polciy</enum>
         <enum value="procedure" short-label="Procedure">Procedure</enum>
         <enum value="guide" short-label="Guidance">Guidance Document</enum>
         <enum value="pia" short-label="P.I.A.">Privacy Impact Assessment</enum>
         <enum value="rob" short-label="R.O.B.">Rules of Behavior</enum>
         <enum value="plan" short-label="Plan">Plan</enum>
         <enum value="system-security-plan" short-label="SSP">System Security Plan</enum>
         <enum value="artifact" short-label="artifact">Artifact</enum>
         <enum value="evidence" short-label="evidence">Evidence</enum>
         <enum value="screen-shot" short-label="screen">Screen Shot</enum>
         <enum value="image" short-label="image">Image</enum>
         <enum value="tool-report" short-label="Report">Tool Report</enum>
         <enum value="raw-tool-output" short-label="Raw">Raw Tool Output</enum>
         <enum value="interview-notes" short-label="Notes">Interview Notes</enum>
         <enum value="questionnaire" short-label="Questions">Questions</enum>
         <enum value="report" short-label="Report">Report</enum>
      </allowed-values>
      <remarkas>Not all values apply to all FedRAMP artifacts.</remarkas>
   </value-set>
```

* **What action would you like to see from the FedRAMP PMO?**

Begin a conversation here. Per discussion with @brianrufgsa, I would like to add cardinality for one of the relevant items to start, probably `control-implementation-status`, as our validation work needs it

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by brianrufgsa** [comment]
@ohsh6o while the FedRAMP Values file has no official recognition with OSCAL today, there is potential for inclusion down the road as part of a larger "Governance" Layer that may appear in OSCAL 2.0.  As such, I'd like to better align this with OSCAL's metaschema syntax, which uses `min-occurs` and `max-occurs` rather than simply `min` and `max`.

If present, the `min-occurs` value must always be an integer. If present, the `max-occurs` must either be an integer (greater than or equal to `min-occurs`) or the word "unbounded", which means there is no upper limit.

For others reading, the concept of operations is as follows:
- An OSCAL file is first validated using the NIST published schema files, which include enforcement for the NIST OSCAL cardinality rules.
- In the FedRAMP Values file, cardinality may **not** be used to relax NIST's cardinality in core OSCAL as this would make OSCAL files invalid. Cardinality may only be specified in this file when FedRAMP requires something more strict. 
- If no cardinality is specified for a specific FedRAMP value, the original core OSCAL cardinality is acceptable to FedRAMP.

For example if core NIST OSCAL allows a field to be optional (`min-occurs="0"`), but the content of that field is required information for a FedRAMP package, then the FedRAMP Values file would specify a cardinality of `min-occurs="1"`.

**Comment by ohsh6o** [comment]
> @ohsh6o while the FedRAMP Values file has no official recognition with OSCAL today, there is potential for inclusion down the road as part of a larger "Governance" Layer that may appear in OSCAL 2.0. As such, I'd like to better align this with OSCAL's metaschema syntax, which uses `min-occurs` and `max-occurs` rather than simply `min` and `max`.

Sorry, this was sloppy note-taking on my part. Very much agree and concur. Apologies for the mix-up.

> If present, the `min-occurs` value must always be an integer. If present, the `max-occurs` must either be an integer (greater than or equal to `min-occurs`) or the word "unbounded", which means there is no upper limit.

This is what I meant to summarize, thanks for clarifying!
 
And thanks for clarifying the other items below as well.

Would it be OK to send back pull requests with just the relevant places cardinality would need to be changed, and start from there, with `control-implementation-status`, and ensuring attributes `min-occurs` and `max-occurs` attributes set, and leet you review at your convenience?

We can also keep it in the 10x fork for now, up to you and your team!

**Comment by ohsh6o** [comment]
Ongoing development, in conjunction with usnistgov/OSCAL#825 makes this obsolete. Closing.
