### ISSUE TITLE
Fedramp information types do not validate against the Oscal Definition

### ISSUE THREAD

**Issue by SilentEsper** [GSA/fedramp-automation#66]
# Describe the bug

Load fedramp data types JSON and validate against Oscal JSON Schema using AJV

# Who is the bug affecting?

Anyone attempting to use fedramp info types json in an oscal oriented program

# What is affected by this bug?

Standards are misconstrued. Nearly approaching OSCAL doesn't really provide the benefits as intended from OSCAL adoption.

# When does this occur?

When Validating Fedramp infor types agains OSCAL informtation-type model

# How do we replicate the issue?

{What are the steps to reproduce the behavior?

Load fedramp data types JSON and validate against Oscal JSON Schema using AJV

And See Validation error.

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

Fedramp Info-types should validate as OSCAL information-types

**Comment by SilentEsper** [comment]
Because Information-types shouldn't have additional properties on the root object:
The additional information provided in the existing JSON should be in the properties array.
Aside from that the id and system should be interpolated differently.
See the contents of this Zip file for a validating version of the fedramp info types
[fedramp-info-types.zip](https://github.com/GSA/fedramp-automation/files/5599464/fedramp-info-types.zip)

**Comment by SilentEsper** [comment]
Furthermore I had to add NA as a impact level on the OSCAL JSON Schema to get it to validate, since I wanted to keep all the information provided by fedramp

**Comment by brianrufgsa** [comment]
@SilentEsper OSCAL doesn't have an information-type model. That information-types file was created for convenience. It was authored in XML and converted to JSON. 

All that said, if there is an established schema to follow, I'm happy to adopt it. Can you provide a link to the schema you are using?

**Comment by SilentEsper** [comment]
On the OSCAL SSP Schema, there is indeed a definition called information-types

https://github.com/usnistgov/OSCAL/blob/master/json/schema/oscal_ssp_schema.json#L918
The system information type you mention actually contains an array of information types right on the definition.

The zip file I previously attached contains the same information in a format that validates against this information-type schema definition. (Although I did add NA as an acceptable value on the oscal schema in order to keep all information)

The fields that violated the schema were:

id, category, *_description,*_explanation, system
I moved category, description and explanation fields into the properties dictionary
and reformatted the id and system according to the schema.

I'll probably be doing the same thing for the other data provided by FEDRAMP like the threats and acceptable values.
Although I haven't checked their compliance status quite yet.

I don't mind to make a pull request when I've completed reformatting fed ramp provided data in this repo for OSCAL compliance.

Have a nice day!

**Comment by brianrufgsa** [comment]
@SilentEsper, sorry for the confusion. NIST uses the term "model" to mean the top-level OSCAL file type (catalog, profile, ssp, assessment-plan, etc.), which was how I took it initially. You are referring to what NIST calls an "assembly", and you are correct there is an `information-type` assembly in the SSP model.

Respectfully, you are trying to use the information-type file in a way that is different than what was intended. I like the idea of better aligning the file with the OSCAL assembly, provided we can first find common ground on the original intention, and provided we don't sacrifice that original intention.

The `information-type` _file_ was created to represent the original 800-60 content, some of which has no corresponding field in OSCAL. In theory, we were only after the `information-type-id`, and wanted to give tool developers a machine-readable version of 800-60, so they could present the list of IDs with all 800-60 supporting details to users. 

Please consider this extract of the information-types file:
```
    <information-type id="C.2.1.2" system="https://doi.org/10.6028/NIST.SP.800-60v2r1">
        <category>Controls and Oversight</category>
        <title>Corrective Action Information Type</title>
        <description>Corrective Action involves the enforcement functions necessary to remedy programs that have been found non-compliant with a given law, regulation, or policy. The recommended security categorization for the corrective action information type is as follows:</description>
        <confidentiality>fips-199-low</confidentiality>
        <availability>fips-199-low</availability>
        <integrity>fips-199-low</integrity>
        <confidentiality_explanation>The confidentiality impact level is the effect of unauthorized disclosure of corrective ...cut... be assigned a moderate confidentiality impact level.</confidentiality_explanation>
        <confidentiality_recommendation>The provisional confidentiality impact level recommended for corrective action information is low.</confidentiality_recommendation>
        <availability_explanation>The availability impact level is based on ...cut... can be expected to have only a limited adverse effect on agency operations, agency assets, or individuals.</availability_explanation>
        <availability_recommendation>The provisional availability impact level recommended for corrective action information is low.</availability_recommendation>
        <integrity_explanation>The consequences of undetected unauthorized modification or destruction of ...cut... only a limited adverse effect on agency operations, assets, or individuals.</integrity_explanation>
        <integrity_recommendation>The provisional integrity impact level recommended for corrective action information is low.</integrity_recommendation>
    </information-type>
```
- `category` is from 800-60 and has no corresponding field in OSCAL.
- `title` from 800-60 may be used as the `title` in OSCAL
- `description` from 800-60 explains NIST's intention for the information type, while `description` in OSCAL describes the actual information handled by the system. (The intent was not to simply duplicate the 800-60 description into OSCAL.)
- The 800-60 `confidentiality`, `availability`, and `integrity` in the file map to `confidentiality-impact/base`, `availability-impact/base`, and `integrity-impact/base` in OSCAL.
- The three explanation and three recommendation fields in the  800-60 file do not map to anything in the OSCAL assembly.

In other words, the category, description, recommendation, and explanation fields are intended to aid the user in selecting information types, but are not intended to appear in the OSCAL file.

The following is the intended use case that resulted in the creation of this file:
- A tool to presents the list of 800-60 information types to a user (by title and description)
- The user reads the description for each type and selects the type(s) appropriate for the system.
- The tool populates the OSCAL assembly with the `title`, `information-type-id` (specifying `system="https://doi.org/10.6028/NIST.SP.800-60v2r1"`), and the three base values.
- The tool then prompts the user to fill in descriptive content about the actual information managed by the system that aligns with this information type.
- The tool then presents the 800-60 content about each impact level and prompts the user to select an impact level. 
- The tool records the user's selection in the `selected` field.
- If the `selected` impact level does not match the `base` impact level, the tool prompts the user for a justification.
- If a justification is required, the tool adds the user's justification to the `adjustment-justification` field.

With those things in mind, it may be reasonable to reorganize the file is it aligns better for those fields that should align, and to add clarity about which fields are intended to copy, and which are not. I think the best we could do to achieve your goals while maintaining the original use case might look something like the following:
```
    <information-type id="C.2.1.2" system="https://doi.org/10.6028/NIST.SP.800-60v2r1">
        <category>Controls and Oversight</category>
        <title>Corrective Action Information Type</title>
        <guidance>Corrective Action involves the enforcement functions necessary to remedy programs that have been found non-compliant with a given law, regulation, or policy. The recommended security categorization for the corrective action information type is as follows:</guidance>
        <confidentiality-impact>
           <base>fips-199-low</base>
           <explanation></explanation>
           <recommendation></recommendation>
        </confidentiality-impact>
        <availability-impact>
           <base>fips-199-low</base>
           <explanation></explanation>
           <recommendation></recommendation>
        </availability-impact>
        <integrity-impact>
           <base>fips-199-low</base>
           <explanation></explanation>
           <recommendation></recommendation>
        </integrity-impact>
</information-type>
```
Thoughts?

**Comment by SilentEsper** [comment]
The information-type assembly has an array field called properties.
in this field it's essentially a dictionary of values in the form of an array. see the /prop definition for all fields.
the information-type assembly has the 
`"additional-fields":"false"` 
setting which indicates the root object should only contain accepted fields.

I placed the additional fields in properties array as seen here:
`
 {
      "information-type-ids": {
        "https://doi.org/10.6028/NIST.SP.800-60v2r1": {
          "id": "C.2.1.2"
        }
      },

      "title": "Corrective Action Information Type",
      "description": "Corrective Action involves the enforcement functions necessary to remedy programs that have been found non-compliant with a given law, regulation, or policy. The recommended security categorization for the corrective action information type is as follows:",
      "confidentiality-impact": {
        "base": "fips-199-low"
      },
      "availability-impact": {
        "base": "fips-199-low"
      },
      "integrity-impact": {
        "base": "fips-199-low"
      },
      "properties": [
        {
          "name": "confidentiality_explanation",
          "value": "The confidentiality impact level is the effect of unauthorized disclosure of corrective action information on the ability of responsible agencies to remedy internal or external programs that have been found non-compliant with a given law, regulation, or policy. Unauthorized disclosure of most corrective action information should have only a limited adverse effect on agency operations, assets, or individuals. Special Factors Affecting Confidentiality Impact Determination: Where more sensitive information is involved, it will probably be personal information subject to the Privacy Act of 1974 or information that is proprietary to a corporation or other organization. Such information will often be assigned a moderate confidentiality impact level. The Privacy Act Information provisional impact levels are documented in the Personal Identity and Authentication information type. Additionally, there are legislative mandates prohibiting unauthorized disclosure of trade secrets. Trade secrets will generally be assigned a moderate confidentiality impact level."
        },
        {
          "name": "confidentiality_recommendation",
          "value": "The provisional confidentiality impact level recommended for corrective action information is low."
        },
        {
          "name": "availability_explanation",
          "value": "The availability impact level is based on the specific mission and the data supporting that mission, not on the time required to re-establish access to the corrective action information. The availability impact is also dependent on whether the data is time-critical. In most cases, disruption of access to corrective action information can be expected to have only a limited adverse effect on agency operations, agency assets, or individuals."
        },
        {
          "name": "availability_recommendation",
          "value": "The provisional availability impact level recommended for corrective action information is low."
        },
        {
          "name": "integrity_explanation",
          "value": "The consequences of undetected unauthorized modification or destruction of corrective action information can conceivably compromise the effectiveness of compliance enforcement actions (e.g., by providing violators with a basis for claiming investigative or enforcement irregularities, thus supporting legal challenges to proposed corrective actions). The integrity impact level is based on the specific mission and the data supporting that mission, not on the time required to detect the modification or destruction of information. Unauthorized modification or destruction of most corrective action information should have only a limited adverse effect on agency operations, assets, or individuals."
        },
        {
          "name": "integrity_recommendation",
          "value": "The provisional integrity impact level recommended for corrective action information is low."
        },
        {
          "name": "category",
          "value": "Controls and Oversight"
        }
      ]
    }

If you wanted to take it a step further you could add a namespace to each property to indicate it's origin and other accepted fields in the realm.


`

**Comment by SilentEsper** [comment]
Admittedly I think the original format is more succinct. but because I'd like to be able to import any Valid OSCAL formatted data,
I'm doing what I can to gather the appropriate default values in OSCAL format.

**Comment by brianrufgsa** [comment]
@SilentEsper I like this! 

This more fully aligns with OSCAL. The only thing I'd change is from `description` to `guidance` so that others don't think the 800-60 information type description is just a copy/paste into the SSP information-type description. That would then become another property. 

Also, if imported into OSCAL, the properties must include `ns` since those property `name` values are not explicitly defined in the core OSCAL content. (NIST calls these "extensions")

The only challenge is in what namespace to use when importing in this case. 
Since these are defined by NIST, not FedRAMP, the team that authors 800-60 should make that decision; however, they have not been involved with this. 

As mentioned, I had only converted the 800-60 information types to a machine-readable format for convenience, and had imagined importing all of the detail. The NIST OSCAL team feels that such content should remain external and can be obtained at any time because the information type is linked by ID, but I'll still try to get their read on the best `ns` value to use.

Worst case, you would be free to define a ns value on behalf of your own organization and apply it as the `ns` value. (`"ns": "http://your.org/ns/oscal"`)

**Comment by SilentEsper** [comment]
I must say having the information type in a JSON form was very convenient! I'm working closely with the AVJ validator so getting it to validate was just a few Regexes away.  The ns for accepted value approach sounds like the OSCAL friendly way.  I'll have to do some research on how to properly format OSCAL namespace extensions for accepted property values.

**Comment by SilentEsper** [comment]
Oscal seems to favor kebab-case, so you could also switch the property names from snake_case to kebab-case

**Comment by SilentEsper** [comment]
https://gist.github.com/SilentEsper/58bfa047c54b5fad503a51b8b45ba4dc

**Comment by ohsh6o** [comment]
@SilentEsper, I am reviewing old issues in the backlog and found this issue. I noticed you had moved to the `prop` style and adapted accordingly. Are we all good here? Should we discuss further in Gitter?

**Comment by SilentEsper** [comment]
Yes I've already transformed the information types into the latest oscal, so for my purposes this issue can be closed.
