### ISSUE TITLE
Present asking for help theme to the FR OSCAL Implementers' Meeting

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#711]

**Comment by jjahearn22** [comment]
@aj-stein-gsa & @Rene2mt here is the link to the slide deck: https://docs.google.com/presentation/d/1WoDjOr1jWgg0QBADG21A-NMSKkhkb0-5/edit#slide=id.p1

Are we covering the next item in the series laid out in #653 ?

**Comment by aj-stein-gsa** [comment]
> @aj-stein-gsa & @Rene2mt here is the link to the slide deck: https://docs.google.com/presentation/d/1WoDjOr1jWgg0QBADG21A-NMSKkhkb0-5/edit#slide=id.p1
> 
> Are we covering the next item in the series laid out in #653 ?

Yep, thats here in 711, asking for help presentation coming up Wednesday. 😄
