### ISSUE TITLE
Present Data Bytes (Sept 2024)

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#712]
### This is a ...

research - something needs to be investigated

### This relates to ...

- Other

### User Story

As a FedRAMP OSCAL community member, I need to periodically get updates on FedRAMP (automation) updates and have a format for dialog with the FedRAMP automation team.

### Goals

This month's data bytes session will focus on the FedRAMP automation team's release and versioning strategy

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by aj-stein-gsa** [comment]
@jjahearn22 can you upload the slides to the branch like others meetings so we can close this out after the meeting that is upcoming? Thanks.

**Comment by jjahearn22** [comment]
This has been completed.
