### ISSUE TITLE
Feature Enhancement - Add Documentation References in Constraints

### ISSUE THREAD

**Issue by Rene2mt** [GSA/fedramp-automation#720]
### This is a ...

request - need something additional provided

### This relates to ...

- [X] the **FedRAMP OSCAL Validations**

### What is your feedback?

As an OSCAL content author, when I validate my content (e.g. OSCAL SSP) using the FedRAMP external constraints, and issues are identified, I would like the validation results to include references to guidance / documentation so that I can better understand what the FedRAMP data and/or data structure requirements are.

Ideally, the validation results would include deep link references to relevant guidance at https://automate.fedramp.gov/documentation 

### Where, exactly?

This would apply to all constraints defined in the FedRAMP external constraint files (e.g., `src/validations/constraints/fedramp-external-*.xml` )

**Comment by aj-stein-gsa** [comment]
OK, @Rene2mt, it would seem it is time to start discussing how we plan the next phases of the alignment work and starting up a style guide soon enough now that #735 is complete.

**Comment by aj-stein-gsa** [comment]
While reviewing the backlog, it seems we wrapped this one up a few weeks ago, potentially with separate issues and PRs and failing to cross-reference this one. I will mark it as done now.
