### ISSUE TITLE
Present hand-writing OSCAL theme to the FR OSCAL Implementers' Meeting

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#731]
- [x] Dependencies: prepare demo material and (potentially update docs) for the following tasks:
    - [x] #729
    - [x] #730
- [x] Update [the slides](https://docs.google.com/presentation/d/1bHLpiEQGjigiZenWn-CaVmIJV7lCpeYf/edit#slide=id.p1) according and ping @Rene2mt and @jjahearn22 for feedback and final review

**Comment by aj-stein-gsa** [comment]
@jjahearn22 I updated the details on the relevant issue for the Wednesday meeting and slides, content from #741 has been integrated into the bullet above.

**Comment by jjahearn22** [comment]
Thanks @aj-stein-gsa! Feel free to close #741 - sorry for the duplicate!

**Comment by aj-stein-gsa** [comment]
Before integrating into the main repo, let's try this out with [a very minimalist repository](https://github.com/aj-stein-gsa/oscal_lab) just to set up the IDE.

**Comment by aj-stein-gsa** [comment]
I would like to run it by @david-waltermire and the rest of the team how to deal with the ☝️ minimalist repo and if we continue to use. Options.

1. Keep it as-is, mark it as archived, revisit later if necessary but let's not overcomplicate things.
2. Continue development on it in a separate repo, here "transferred" to GSA or appropriate GitHub org, and flesh out more on it.
3. Integrate it into the fedramp-autmation repository and not make it separate, continue work as needed, archive this repo at the end like 1.

Once we upload the presentation and decide on the decision above, we can mark this issue and dependent tasks as completed closed.

**Comment by wandmagic** [comment]
I think bring it over to GSA or metaschema org and bring this in. I think it would be neat to have it as a Template repo that others can start a fresh package from

**Comment by Rene2mt** [comment]
I like option # 2.  Transfer over to GSA (or metaschema org as @wandmagic  proposed)  and continue to flesh it out more as needed.

**Comment by aj-stein-gsa** [comment]
Updating the site in a separate unrelated PR in the website, but it will cover this and a bunch slides that are not to be in the repo anymore. Marking the presentation tasking issue here as resolved.
