### ISSUE TITLE
Metapath function support needed for adding or improving FedRAMP constraints

### ISSUE THREAD

**Issue by Gabeblis** [GSA/fedramp-automation#734]
### This is a ...

improvement - something could be better

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### User Story

As a developer working on writing constraints, I want metaschema-java to support crucial XPath functions,
so that I can proceed with implementing and validating constraints without being blocked.

### Goals

Enable support for the following XPath functions in metaschema-java:
- [x] https://github.com/metaschema-framework/metaschema-java/issues/132
- [x] https://github.com/metaschema-framework/metaschema-java/issues/133
- [x] https://github.com/metaschema-framework/metaschema-java/issues/134
- [x] https://github.com/metaschema-framework/metaschema-java/issues/135

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

### Other information

Currently, the development of several constraints is halted because metaschema-java lacks support for essential XPath functions. These functions are critical to writing and validating certain constraints in our schema. Without them, we are unable to proceed with development and testing, leading to delays in the project timeline. This user story aims to ensure that metaschema-java provides the necessary support for these XPath functions to unblock development and enable the proper writing of constraints.

**Comment by wandmagic** [comment]
filter would also be great

**Comment by aj-stein-gsa** [comment]
I am gonna work on a cross-reference issue in [metaschema-java](https://github.com/metaschema-framework/metaschema-java) so these functions and their capabilities "bubble up" into `oscal-cli` soon enough and we can update the version in the container spec.

Thank you gentlemen, updates incoming! 😎

**Comment by aj-stein-gsa** [comment]
While reviewing old issues, I realized after the last metaschema-java release this tracker issue was not updated. This work has been completed since a few week ago and developers can use this function accordingly.
