### ISSUE TITLE
Support Oscal RC1

### ISSUE THREAD

**Issue by SilentEsper** [GSA/fedramp-automation#74]
# Describe the bug

Fedramp baselines are still using oscal milestone 3 please update to RC1

# Who is the bug affecting?

anyone trying to use fedramp baselines & latest version of oscal 

# What is affected by this bug?

baselines require milestone3=>RC1 conversion to interop with latest oscal

# Expected behavior (i.e. solution)

Update Baseline Json files

**Comment by david-waltermire-nist** [comment]
The baselines have been updated to OSCAL 1.0.0 RC1.
