### ISSUE TITLE
[Feedback]: Guidance should include the responsible-party assembly for CSP Name

### ISSUE THREAD

**Issue by vmangat** [GSA/fedramp-automation#747]
### This is a ...

request - need something additional provided

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP OSCAL Validations**

### What is your feedback?

The guidance need to be updated to include a responsible-party assembly tying the CSP party to the role-id "cloud-service-provider"

### Where, exactly?

https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/
![image](https://github.com/user-attachments/assets/6a611c34-e904-4d1b-8475-5cc75c8a81d1)

**Comment by aj-stein-gsa** [comment]
Hi @vmangat, I was reviewing the backlog for items marked triage needed and this request was very timely. It is not just for CSP, but given your request, I believe we are in the process of resolving this by updating a constraint and associated documentation for #874 in https://github.com/GSA/automate.fedramp.gov/pull/112. Stay tuned. I will mark this issue as in review, as it will be closed with the #112 PR potentially.

**Comment by aj-stein-gsa** [comment]
I will be marking this issue as ready to ship and complete as resolved by cross-linked issue #874.
