### ISSUE TITLE
Container does not include most recent release of `oscal-cli` in image

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#752]
### This relates to ...

- [X] the **FedRAMP OSCAL Validations**

### What happened?

As reported by @devbytyler and perhaps others on the call, the current development version of the container has one version behind of `oscal-cli`, version 2.0.2, not 2.1.0.

### Relevant log output

```Shell
docker pull ghcr.io/gsa/fedramp-automation/validation-tools:5da931880619f232c54a8424318b16cf72539565 # current develop commit is 5da9318
$ docker run --rm -it -v $(pwd):/data ghcr.io/gsa/fedramp-automation/validation-tools:5da931880619f232c54a8424318b16cf72539565 --version  
oscal-cli 2.0.2 built at 2024-08-20 13:19 from branch 7df9154fb123ed6515ea51bacc65b7489da82717 (7df9154) at https://github.com/metaschema-framework/oscal-cli
liboscal-java  built at 2024-08-20 04:25 from branch 827cfe5b63f0f1f4905fc82c76d7e68733fcd271 (827cfe5) at https://github.com/metaschema-framework/liboscal-java
oscal v1.1.2 built at 2024-08-20 04:25 from branch 4f02dac6f698efda387cc5f55bc99581eaf494b6 (4f02dac) at https://github.com/usnistgov/OSCAL.git
metaschema-java 1.0.2 built at 2024-08-19T18:05:06+0000 from branch 76fe3c9dcebe45223d83034f4836510e3a347ba7 (76fe3c9) at https://github.com/metaschema-framework/metaschema-java
metaschema  built at 2024-08-19T18:05:06+0000 from branch 894b2238764c8732623a3894f0c236625ca5a686 (894b223) at https://github.com/metaschema-framework/metaschema.git
```

### How do we replicate this issue?

1. Run above command.
2. Check output of version info.

### Where, exactly?

Container builds for tools combined with the constraints in this repo's automation.

**Comment by devbytyler** [comment]
You are so great at following up. Thanks!

**Comment by aj-stein-gsa** [comment]
> I am amazed at your following up-skills. Thanks @aj-stein-gsa!

That's a team effort, sir, not just an AJ thing. Admiring fans can write to oscal@fedramp.gov to let our team leads know. We are here to serve. 🫡
