### ISSUE TITLE
Knowledge check and review installation, asking for help, and writing OSCAL concepts

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#758]
### This is a ...

improvement - something could be better

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [x] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)

### User Story

As a DAP pilot participant, (or an OSCAL implementor interested in learning more), I may or may not have attended the last several walkthroughs, but I need all of the pieces to be put together so that in one follow-along session, I can understand how to best install the tooling, use it on my own SSPs, troubleshoot, and submit issues. 

### Goals

Plan and deliver a walkthrough that covers containerized installation, running the tool, looking at the results, identifying an issue or unexpected performance, getting the logs, and submitting a github issue. 

Preparation:
- [ ] Walkthrough installation and running command line tool a couple of times, figure out how to undo it quickly
- [ ] Identify a bug and figure out how to replicate it. Adapt SSP to replicate issue during walkthrough
- [ ] Upload adapted SSP to github
- [ ] Walkthrough getting logs/troubleshooting a couple of times
- [ ] Walkthrough submitting an issue a couple of times
- [ ] Put it all together and run through at least twice
- [ ] Create an overview slide

**Comment by aj-stein-gsa** [comment]
@kyhu65867 per conversation in the chat do you want to work on this and make it your own? (I could put deeper requirements from Google Chat, if you would like me to do that for you, let me know, I am flexible.)

**Comment by jjahearn22** [comment]
@kyhu65867 & @Rene2mt here is the slide deck for this week: https://docs.google.com/presentation/d/1Z51MbJRHqmKn6iGj7-fGRi79FAWb4L5l/edit#slide=id.p1

Rene, I think we'll likely just need the general updates section updated. Kylie, I kept in a couple of high-level slides for the DAP pilot as an intro to the topic, but I believe most things you cover will be off slides?
