### ISSUE TITLE
[Feedback]: Collapsible sections in the readme and other documentation

### ISSUE THREAD

**Issue by kyhu65867** [GSA/fedramp-automation#765]
### This is a ...

kudos - want to encourage something helpful

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP OSCAL Validations**

### What is your feedback?

This link: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections has information about how to collapse sections in readmes, etc. I want to do this in different READMEs so that people aren't overwhelmed by walls of text and only see what's important

### Where, exactly?

README

**Comment by aj-stein-gsa** [comment]
Did we implement those in the draft PR for #771?

**Comment by aj-stein-gsa** [comment]
This work was completed as part of https://github.com/GSA/fedramp-automation/pull/771.
