### ISSUE TITLE
Add data-center location constraints to FedRAMP OSCAL Documentation

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#767]
### This is a ...

fix - something needs to be different

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [X] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### User Story

When validating an OSCAL SSP against the fedramp-external-constraints.xml, the oscal-cli yields the following errors:
[ERROR] [/system-security-plan/metadata[1]] There must be at least two (2) data centers listed.
[ERROR] [/system-security-plan/metadata[1]] There must be a single primary data center.
[ERROR] [/system-security-plan/metadata[1]] There must be one or more alternate data center(s).
I understand the need for these constraints, but these are not reflected in the [FedRAMP OSCAL Documentation](https://automate.fedramp.gov/documentation/) anywhere that I could find. 

### Goals

Add these constraints to the [FedRAMP OSCAL Documentation](https://automate.fedramp.gov/documentation/) so that OSCAL users are able to appropriately define their locations without having to validate and review errors first.

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by aj-stein-gsa** [comment]
It would seem that somehow I did not properly track this issue and it was resolved with #85.
