### ISSUE TITLE
[Feedback]: FedRAMP Constraint - point of contact for an authorizing official

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#768]
### This is a ...

question - need to understand something

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [X] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### What is your feedback?

When validating an OSCAL SSP with the oscal-cli and fedramp-external-constraints.xml, we are getting the following error:
[ERROR] [/system-security-plan/metadata[1]] A FedRAMP SSP must define a role for the point of contact for an authorizing official.
We have a "authorizing-official" role defined in the SSP, and parties associated with it in responsible-parties, but we are still getting this error. We were wondering if this error is referencing a different role id? Or if this could be a bug with the constraints/validation.

### Where, exactly?

Enhanced oscal-cli, v2.1.0
OSCAL SSP's

**Comment by Rene2mt** [comment]
PR GSA/automate.fedramp.gov#60 addresses this documentation issue.

**Comment by aj-stein-gsa** [comment]
Hi @Telos-sa, I just wanted to update you as we merged in work in the new constraints prior to an upcoming release. Regarding this feedback below we have updates.

> A FedRAMP SSP must define a role for the point of contact for an authorizing official. We have a "authorizing-official" role defined in the SSP, and parties associated with it in responsible-parties, but we are still getting this error. We were wondering if this error is referencing a different role id? Or if this could be a bug with the constraints/validation.

Internal staff confirm explicitly separate points-of-contact roles were removed from the non-OSCAL templates and are no longer used, so we backed out documentation changes to move them in. Such constraints were defined in older documentation and Schematron implementation notes, but that has not been valid for some time.

I will mark this issue as closed for now. Feel free to re-open to ask for clarification or discuss further if I closed it in error. 👋
