### ISSUE TITLE
[Question]: How to identify what caused a runtime error

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#782]
### This is a ...

question - need to understand something

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### What is your feedback?

When validating an OSCAL SSP using the enhanced oscal-cli (without any constraints) we are getting the following error:

Validating 'file:///Users/13994/Desktop/SA%20Git/xacta360-xde-oscal-schema-export/FedRAMP%20SSP%20-%2024.03%20(2024-10-16T163251Z).json' as JSON.
An uncaught runtime error occurred. null

We are having some trouble identifying what could be causing this runtime error. We were hoping you could provide some insight to help us identify what is causing this error/where the error is in the OSCAL model. Do you have any suggestions or steps to take for identifying the cause?

### Where, exactly?

- OSCAL SSP v1.1.2
- enhanced oscal-cli v2.2.0

**Comment by aj-stein-gsa** [comment]
Excellent question, here you go.

https://github.com/GSA/fedramp-automation/blob/develop/src/validations/constraints/CONTRIBUTING.md#troubleshooting
