### ISSUE TITLE
Add check for profile or catalog resolution in SSP

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#793]
### This is a ...

improvement - something could be better

### This relates to ...

- [X] the **FedRAMP OSCAL Validations**

### User Story

As a maintainer of a digital authorization package, to know my SSP is referencing controls from a valid catalog, I would like my software to check the `import-profile/@href` _and_ ensure there are resolved controls in it.

### Goals

- [x] Check profile resolution is accurate
- [x] Document a heuristic to know that at least one FedRAMP-worthy control (not just a NIST control) can be found for control implementation. If the test is not met, fail with a `CRITICAL` error.
- [x] Add functionality to test a constraint against multiple test files to ensure that it successfully passes in all possible scenarios.

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by vmangat** [comment]
Please refer to #745 relates to this item as well

**Comment by aj-stein-gsa** [comment]
> Please refer to #745 relates to this item as well

Sure thing, but that request does pertain to changing the URL style in the baseline profiles and resolved catalogs yes? At the constraint layer, that part can be obscured away. But we can keep that in mind.
