### ISSUE TITLE
Data Center constraints do not conform with upstream OSCAL expectations

### ISSUE THREAD

**Issue by kyhu65867** [GSA/fedramp-automation#818]
### This relates to ...

- [X] the **FedRAMP OSCAL Validations**

### What happened?

When @aj-stein-gsa changed "name" to a value of "type" in the ssp-ALL-VALID file, test cases for the data center constraints broke. This is because the constraints are written to expect a "name" value of "data-center".

Common practice is for the name field to equal "type" and for the value field to equal "data-center". Thus, Constraints and test cases need to be adjusted accordingly. 
![Screenshot 2024-10-24 at 11 41 07 AM](https://github.com/user-attachments/assets/f423a7be-932a-4657-bce2-2ce5feafd26f)

### How do we replicate this issue?

Change ssp-all-VALID to the correct syntax and watch the test harness fail. 

### Where, exactly?

- Changes need to be made in ssp-all-valid to make it conformant. 
- Subsequently, changes need to be made in fedramp-external-constraints to the data center related constraints
- Finally, changes need to be made to the unit tests for these constraints

### Other relevant details

Another issue I noticed is that the unit tests are split up into multiple files, like "ssp-data-center-alternate-INVALID", but there are multiple things wrong in that file, AKA the country code is also incorrect. I think this defeats the purpose of unit tests, because how do we know if it is invalid because the alternate is invalid if there are multiple issues appearing? I will try to address this but I don't know how widespread of a problem this is

**Comment by aj-stein-gsa** [comment]
This can move from blocked to in review and ready to ship once https://github.com/GSA/automate.fedramp.gov/pull/96 is merged.
