### ISSUE TITLE
Create an Issue Template for Constraint Work

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#822]
### This is a ...

improvement - something could be better

### User Story

As a member of the FedRAMP Automation Team, I would like an issue template specifically aligned to individual constraint tasks and our emerging standards for definition of done, testing, and constraint definition.

### Goals

Create an issue template that streamlines our issue generation for specific constraint tasks.

### Dependencies

none.

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

### Other information

none.

**Comment by aj-stein-gsa** [comment]
Brian and I worked on setting up a branch after we worked around some issues with branch protections I just became aware of. 😦 

More to follow after, thanks for @brian-ruf for the heads up on the `ac0a47f4df6f30fc6581a9d2320e2165bd88e502` commit issue (that bit is for an issue I shall draft).

**Comment by aj-stein-gsa** [comment]
@aj-stein-gsa needs to formally re-review very shortly. 😉
