### ISSUE TITLE
Present validation analysis theme to the FR OSCAL Implementers' Meeting

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#832]

**Comment by aj-stein-gsa** [comment]
Per discussion in the standup today and prep for this presentation, we may want to address (if possibly) how the constraints and tools apply to them _if_ they do not integrate them directly into their own production software and environment (they and their environment being for CSP; GRC developer; tool developer; 3PAO; agency customer; et cetera).

**Comment by jjahearn22** [comment]
@aj-stein-gsa & @Rene2mt here is the link to the slides: https://docs.google.com/presentation/d/15jBG1WzrfZOlKxcgdap5eho-b6NtaqCS/edit#slide=id.g2a22e0c5c63_1_175 I'll be able to attend meetings tomorrow to cover any questions tomorrow

**Comment by aj-stein-gsa** [comment]
Uploading the slides to GSA/automate.fedramp.gov#73, moving this to done.
