### ISSUE TITLE
Check for CUI marking on all digital authorization package content

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#836]
### Constraint Task

As a digital authorization package maintainer, to meet FedRAMP requirements, avoid passbacks, and properly identify data security requirements while doing so, I want to know all my documents in the package have properly selected the correct data classification or return a passback error.

#### Goal

Identify package documents that _require_ a CUI marking (so all but catalogs and profiles; those are inherently not controlled, they go everywhere)

#### Syntax

- [x] An [expect constraint](https://pages.nist.gov/metaschema/specification/syntax/constraints/#expect-constraints) to check that for `/(assessment-plan|assessment-results|plan-of-action-and-milestones|system-security-plan)/metadata/prop[@name="marking"]/@value` to return a message with `@level="ERROR"` for a document that does not `prop[@name="marking"]/@value` = `cui`. 
- ~An [allowed-values constraint](https://pages.nist.gov/metaschema/specification/syntax/constraints/#allowed-values-constraints) constraint to check the syntax `/(assessment-plan|assessment-results|plan-of-action-and-milestones|system-security-plan)/metadata/prop[@name="marking"]/@value` for an allowed value of `cui`. This enumeration will allow undefined values `@allow-other="yes"`, see allowed-values guidance below.~

VALID:

```xml
<system-security-plan>
  <metadata>
    <prop name="marking" value="cui"/>
  </metadata>   
</system-security-plan>
```

```xml
<assessment-plan>
  <metadata>
    <prop name="marking" value="cui"/>
  </metadata>   
</assessment-plan>
```

INVALID:

```xml
<system-security-plan>
  <metadata>
    <!-- no marking prop at all -->
  </metadata>   
</system-security-plan>
```

```xml
<assessment-plan>
  <metadata>
    <!-- no marking prop at all -->
  </metadata>   
</assessment-plan>
```

### Syntax Type

This is optional core OSCAL syntax.

### Allowed Values

There are only NIST-defined allowed values.

### Metapath(s) to Content

```xslt
/(assessment-plan|assessment-results|plan-of-action-and-milestones|system-security-plan)/metadata/prop[@name="marking"]/@value
```

### Purpose of the OSCAL Content

- [x] Check for proper data classification of package documents (SSP; SAP; SAR; POAMs)

### Dependencies

N/A

### Acceptance Criteria

- [x] All [OSCAL adoption content](http://automate.fedramp.gov/) affected by the change in this issue have been updated in accordance with the Documentation Standards.
  - [x] Explanation is present and accurate
  - [x] sample content is present and accurate
  - [x] [Metapath](https://pages.nist.gov/metaschema/specification/syntax/metapath/) is present,  accurate, and does not throw a syntax exception using `oscal-cli metaschema metapath eval -e "expression"`. 
- [x] All constraints associated with the review task have been created
- [x] The appropriate example OSCAL file is updated with content that demonstrates the FedRAMP-compliant OSCAL presentation.
- [x] The constraint conforms to the FedRAMP Constraint Style Guide. 
  - [x] All automated and manual review items that identify non-conformance are addressed; **or** technical leads (David Waltermire; AJ Stein) have approved the PR and “override” the style guide requirement.
- [ ] Known good test content is created for unit testing.
- [ ] Known bad test content is created for unit testing.
- [ ] Unit testing is configured to run both known good and known bad test content examples.
- [ ] Passing and failing unit tests, and corresponding test vectors in the form of known valid and invalid OSCAL test files, are created or updated for each constraint.
- [x] A Pull Request (PR) is submitted that fully addresses the goals section of the User Story in the issue. 
- [x] This issue is referenced in the PR.

### Other information

Part of epic #804.

**Comment by aj-stein-gsa** [comment]
@DimitriZhurkin please review the checklist tomorrow and be ready to confirm if this issue, now that PRs are closed, is ready to ship.

**Comment by DimitriZhurkin** [comment]
Technically, unit tests exist only for SSP. Work on SAP, SAR, and POA&M hasn't started yet.

**Comment by aj-stein-gsa** [comment]
> Should we do that now, or scope this issue to just the SSP which is already done, and create separate issues for adding unit test vectors for the SAP, SAR, and POA&M?

If we need to consider the scope of work to be everything but the constraint `@test` logic, so docs and examples, which makes the work effort  more clear and faster? I don't have a strong opinion on this one, so I can just pick if others do not. 😄

**Comment by aj-stein-gsa** [comment]
Per conversation in a backlog meeting at the time of this writing, for low-risk cross-model `//metadata` constraints, we can accept not explicitly adding per-model tests for such requirements that are also covered in generic documentation for cross-model requirements, I am happy to accept the included tests and examples as-is and the work is ready to release.
