### ISSUE TITLE
OSCAL Profiles Responsible Parties Reference Unknown UUIDs

### ISSUE THREAD

**Issue by rgauss** [GSA/fedramp-automation#90]
# Describe the bug

The baseline OSCAL profiles responsible parties section references unknown UUIDs.

Many profiles list `4aa7b203-318b-4cde-96cf-feaeffc3a4b7` as values for the `prepared-by` and `fedramp-pmo` roles, yet the `FedRAMP PMO` party in those profiles has a UUID of `8cc0b8e5-9650-4d5f-9796-316f05fa9a2d`.

# Who is the bug affecting?

Anyone using baseline OSCAL profiles.

# What is affected by this bug?

The ability to resolve responsible parties in baselines.

# When does this occur?

Always.

**Comment by ohsh6o** [comment]
👋 Thank you for the report, @rgauss, I will take a look, potentially PR a solution, and get back to you to review that fix if applicable.

**Comment by ohsh6o** [comment]
@rgauss, I will have the pipeline generate the data, but I updated core source files. You can take a look (I cannot assign reviewers from outside the GSA org, but I welcome community feedback).

Per discussion with NIST OSCAL developers, I am not certain NIST or FedRAMP is committing to permanent use of any UUID in the `party` or `role` fields, and they meant to be consistent for inter-document references for now, but not for permanence across baselines or long-lived artifacts at this point in time.

I just wanted to be clear about expectations, even if we revert to the long-standing one, there is no guarantee it will remain `8cc0b8e5-9650-4d5f-9796-316f05fa9a2d` by way of policy. If you have more questions or concerns about that, please feel to open up a policy-related PMO issue in the Github board.
